// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

// Import schema type
import { SchemaType } from "@latticexyz/schema-type/src/solidity/SchemaType.sol";

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { Schema, SchemaLib } from "@latticexyz/store/src/Schema.sol";
import { PackedCounter, PackedCounterLib } from "@latticexyz/store/src/PackedCounter.sol";

bytes32 constant _tableId = bytes32(abi.encodePacked(bytes16(""), bytes16("BuffStatus")));
bytes32 constant BuffStatusTableId = _tableId;

struct BuffStatusData {
  bytes32 buffId;
  uint256 startTime;
}

library BuffStatus {
  /** Get the table's schema */
  function getSchema() internal pure returns (Schema) {
    SchemaType[] memory _schema = new SchemaType[](2);
    _schema[0] = SchemaType.BYTES32;
    _schema[1] = SchemaType.UINT256;

    return SchemaLib.encode(_schema);
  }

  function getKeySchema() internal pure returns (Schema) {
    SchemaType[] memory _schema = new SchemaType[](3);
    _schema[0] = SchemaType.UINT8;
    _schema[1] = SchemaType.BYTES32;
    _schema[2] = SchemaType.UINT32;

    return SchemaLib.encode(_schema);
  }

  /** Get the table's metadata */
  function getMetadata() internal pure returns (string memory, string[] memory) {
    string[] memory _fieldNames = new string[](2);
    _fieldNames[0] = "buffId";
    _fieldNames[1] = "startTime";
    return ("BuffStatus", _fieldNames);
  }

  /** Register the table's schema */
  function registerSchema() internal {
    StoreSwitch.registerSchema(_tableId, getSchema(), getKeySchema());
  }

  /** Register the table's schema (using the specified store) */
  function registerSchema(IStore _store) internal {
    _store.registerSchema(_tableId, getSchema(), getKeySchema());
  }

  /** Set the table's metadata */
  function setMetadata() internal {
    (string memory _tableName, string[] memory _fieldNames) = getMetadata();
    StoreSwitch.setMetadata(_tableId, _tableName, _fieldNames);
  }

  /** Set the table's metadata (using the specified store) */
  function setMetadata(IStore _store) internal {
    (string memory _tableName, string[] memory _fieldNames) = getMetadata();
    _store.setMetadata(_tableId, _tableName, _fieldNames);
  }

  /** Get buffId */
  function getBuffId(uint8 targetType, bytes32 targetId, uint32 buffType) internal view returns (bytes32 buffId) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(targetType));
    _keyTuple[1] = targetId;
    _keyTuple[2] = bytes32(uint256(buffType));

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 0);
    return (Bytes.slice32(_blob, 0));
  }

  /** Get buffId (using the specified store) */
  function getBuffId(
    IStore _store,
    uint8 targetType,
    bytes32 targetId,
    uint32 buffType
  ) internal view returns (bytes32 buffId) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(targetType));
    _keyTuple[1] = targetId;
    _keyTuple[2] = bytes32(uint256(buffType));

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 0);
    return (Bytes.slice32(_blob, 0));
  }

  /** Set buffId */
  function setBuffId(uint8 targetType, bytes32 targetId, uint32 buffType, bytes32 buffId) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(targetType));
    _keyTuple[1] = targetId;
    _keyTuple[2] = bytes32(uint256(buffType));

    StoreSwitch.setField(_tableId, _keyTuple, 0, abi.encodePacked((buffId)));
  }

  /** Set buffId (using the specified store) */
  function setBuffId(IStore _store, uint8 targetType, bytes32 targetId, uint32 buffType, bytes32 buffId) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(targetType));
    _keyTuple[1] = targetId;
    _keyTuple[2] = bytes32(uint256(buffType));

    _store.setField(_tableId, _keyTuple, 0, abi.encodePacked((buffId)));
  }

  /** Get startTime */
  function getStartTime(uint8 targetType, bytes32 targetId, uint32 buffType) internal view returns (uint256 startTime) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(targetType));
    _keyTuple[1] = targetId;
    _keyTuple[2] = bytes32(uint256(buffType));

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 1);
    return (uint256(Bytes.slice32(_blob, 0)));
  }

  /** Get startTime (using the specified store) */
  function getStartTime(
    IStore _store,
    uint8 targetType,
    bytes32 targetId,
    uint32 buffType
  ) internal view returns (uint256 startTime) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(targetType));
    _keyTuple[1] = targetId;
    _keyTuple[2] = bytes32(uint256(buffType));

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 1);
    return (uint256(Bytes.slice32(_blob, 0)));
  }

  /** Set startTime */
  function setStartTime(uint8 targetType, bytes32 targetId, uint32 buffType, uint256 startTime) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(targetType));
    _keyTuple[1] = targetId;
    _keyTuple[2] = bytes32(uint256(buffType));

    StoreSwitch.setField(_tableId, _keyTuple, 1, abi.encodePacked((startTime)));
  }

  /** Set startTime (using the specified store) */
  function setStartTime(
    IStore _store,
    uint8 targetType,
    bytes32 targetId,
    uint32 buffType,
    uint256 startTime
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(targetType));
    _keyTuple[1] = targetId;
    _keyTuple[2] = bytes32(uint256(buffType));

    _store.setField(_tableId, _keyTuple, 1, abi.encodePacked((startTime)));
  }

  /** Get the full data */
  function get(
    uint8 targetType,
    bytes32 targetId,
    uint32 buffType
  ) internal view returns (BuffStatusData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(targetType));
    _keyTuple[1] = targetId;
    _keyTuple[2] = bytes32(uint256(buffType));

    bytes memory _blob = StoreSwitch.getRecord(_tableId, _keyTuple, getSchema());
    return decode(_blob);
  }

  /** Get the full data (using the specified store) */
  function get(
    IStore _store,
    uint8 targetType,
    bytes32 targetId,
    uint32 buffType
  ) internal view returns (BuffStatusData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(targetType));
    _keyTuple[1] = targetId;
    _keyTuple[2] = bytes32(uint256(buffType));

    bytes memory _blob = _store.getRecord(_tableId, _keyTuple, getSchema());
    return decode(_blob);
  }

  /** Set the full data using individual values */
  function set(uint8 targetType, bytes32 targetId, uint32 buffType, bytes32 buffId, uint256 startTime) internal {
    bytes memory _data = encode(buffId, startTime);

    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(targetType));
    _keyTuple[1] = targetId;
    _keyTuple[2] = bytes32(uint256(buffType));

    StoreSwitch.setRecord(_tableId, _keyTuple, _data);
  }

  /** Set the full data using individual values (using the specified store) */
  function set(
    IStore _store,
    uint8 targetType,
    bytes32 targetId,
    uint32 buffType,
    bytes32 buffId,
    uint256 startTime
  ) internal {
    bytes memory _data = encode(buffId, startTime);

    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(targetType));
    _keyTuple[1] = targetId;
    _keyTuple[2] = bytes32(uint256(buffType));

    _store.setRecord(_tableId, _keyTuple, _data);
  }

  /** Set the full data using the data struct */
  function set(uint8 targetType, bytes32 targetId, uint32 buffType, BuffStatusData memory _table) internal {
    set(targetType, targetId, buffType, _table.buffId, _table.startTime);
  }

  /** Set the full data using the data struct (using the specified store) */
  function set(
    IStore _store,
    uint8 targetType,
    bytes32 targetId,
    uint32 buffType,
    BuffStatusData memory _table
  ) internal {
    set(_store, targetType, targetId, buffType, _table.buffId, _table.startTime);
  }

  /** Decode the tightly packed blob using this table's schema */
  function decode(bytes memory _blob) internal pure returns (BuffStatusData memory _table) {
    _table.buffId = (Bytes.slice32(_blob, 0));

    _table.startTime = (uint256(Bytes.slice32(_blob, 32)));
  }

  /** Tightly pack full data using this table's schema */
  function encode(bytes32 buffId, uint256 startTime) internal pure returns (bytes memory) {
    return abi.encodePacked(buffId, startTime);
  }

  /** Encode keys as a bytes32 array using this table's schema */
  function encodeKeyTuple(
    uint8 targetType,
    bytes32 targetId,
    uint32 buffType
  ) internal pure returns (bytes32[] memory _keyTuple) {
    _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(targetType));
    _keyTuple[1] = targetId;
    _keyTuple[2] = bytes32(uint256(buffType));
  }

  /* Delete all data for given keys */
  function deleteRecord(uint8 targetType, bytes32 targetId, uint32 buffType) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(targetType));
    _keyTuple[1] = targetId;
    _keyTuple[2] = bytes32(uint256(buffType));

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /* Delete all data for given keys (using the specified store) */
  function deleteRecord(IStore _store, uint8 targetType, bytes32 targetId, uint32 buffType) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(targetType));
    _keyTuple[1] = targetId;
    _keyTuple[2] = bytes32(uint256(buffType));

    _store.deleteRecord(_tableId, _keyTuple);
  }
}
