// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

// Import schema type
import { SchemaType } from "@latticexyz/schema-type/src/solidity/SchemaType.sol";

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { Schema, SchemaLib } from "@latticexyz/store/src/Schema.sol";
import { PackedCounter, PackedCounterLib } from "@latticexyz/store/src/PackedCounter.sol";

bytes32 constant _tableId = bytes32(abi.encodePacked(bytes16(""), bytes16("CatAttributes")));
bytes32 constant CatAttributesTableId = _tableId;

struct CatAttributesData {
  bool sex;
  bytes32 fatherId;
  bytes32 motherId;
  bytes32 hobbyId;
  uint256 personality;
  uint256 skin;
  uint256 birthTime;
}

library CatAttributes {
  /** Get the table's schema */
  function getSchema() internal pure returns (Schema) {
    SchemaType[] memory _schema = new SchemaType[](7);
    _schema[0] = SchemaType.BOOL;
    _schema[1] = SchemaType.BYTES32;
    _schema[2] = SchemaType.BYTES32;
    _schema[3] = SchemaType.BYTES32;
    _schema[4] = SchemaType.UINT256;
    _schema[5] = SchemaType.UINT256;
    _schema[6] = SchemaType.UINT256;

    return SchemaLib.encode(_schema);
  }

  function getKeySchema() internal pure returns (Schema) {
    SchemaType[] memory _schema = new SchemaType[](1);
    _schema[0] = SchemaType.BYTES32;

    return SchemaLib.encode(_schema);
  }

  /** Get the table's metadata */
  function getMetadata() internal pure returns (string memory, string[] memory) {
    string[] memory _fieldNames = new string[](7);
    _fieldNames[0] = "sex";
    _fieldNames[1] = "fatherId";
    _fieldNames[2] = "motherId";
    _fieldNames[3] = "hobbyId";
    _fieldNames[4] = "personality";
    _fieldNames[5] = "skin";
    _fieldNames[6] = "birthTime";
    return ("CatAttributes", _fieldNames);
  }

  /** Register the table's schema */
  function registerSchema() internal {
    StoreSwitch.registerSchema(_tableId, getSchema(), getKeySchema());
  }

  /** Register the table's schema (using the specified store) */
  function registerSchema(IStore _store) internal {
    _store.registerSchema(_tableId, getSchema(), getKeySchema());
  }

  /** Set the table's metadata */
  function setMetadata() internal {
    (string memory _tableName, string[] memory _fieldNames) = getMetadata();
    StoreSwitch.setMetadata(_tableId, _tableName, _fieldNames);
  }

  /** Set the table's metadata (using the specified store) */
  function setMetadata(IStore _store) internal {
    (string memory _tableName, string[] memory _fieldNames) = getMetadata();
    _store.setMetadata(_tableId, _tableName, _fieldNames);
  }

  /** Get sex */
  function getSex(bytes32 catId) internal view returns (bool sex) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = catId;

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 0);
    return (_toBool(uint8(Bytes.slice1(_blob, 0))));
  }

  /** Get sex (using the specified store) */
  function getSex(IStore _store, bytes32 catId) internal view returns (bool sex) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = catId;

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 0);
    return (_toBool(uint8(Bytes.slice1(_blob, 0))));
  }

  /** Set sex */
  function setSex(bytes32 catId, bool sex) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = catId;

    StoreSwitch.setField(_tableId, _keyTuple, 0, abi.encodePacked((sex)));
  }

  /** Set sex (using the specified store) */
  function setSex(IStore _store, bytes32 catId, bool sex) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = catId;

    _store.setField(_tableId, _keyTuple, 0, abi.encodePacked((sex)));
  }

  /** Get fatherId */
  function getFatherId(bytes32 catId) internal view returns (bytes32 fatherId) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = catId;

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 1);
    return (Bytes.slice32(_blob, 0));
  }

  /** Get fatherId (using the specified store) */
  function getFatherId(IStore _store, bytes32 catId) internal view returns (bytes32 fatherId) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = catId;

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 1);
    return (Bytes.slice32(_blob, 0));
  }

  /** Set fatherId */
  function setFatherId(bytes32 catId, bytes32 fatherId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = catId;

    StoreSwitch.setField(_tableId, _keyTuple, 1, abi.encodePacked((fatherId)));
  }

  /** Set fatherId (using the specified store) */
  function setFatherId(IStore _store, bytes32 catId, bytes32 fatherId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = catId;

    _store.setField(_tableId, _keyTuple, 1, abi.encodePacked((fatherId)));
  }

  /** Get motherId */
  function getMotherId(bytes32 catId) internal view returns (bytes32 motherId) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = catId;

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 2);
    return (Bytes.slice32(_blob, 0));
  }

  /** Get motherId (using the specified store) */
  function getMotherId(IStore _store, bytes32 catId) internal view returns (bytes32 motherId) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = catId;

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 2);
    return (Bytes.slice32(_blob, 0));
  }

  /** Set motherId */
  function setMotherId(bytes32 catId, bytes32 motherId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = catId;

    StoreSwitch.setField(_tableId, _keyTuple, 2, abi.encodePacked((motherId)));
  }

  /** Set motherId (using the specified store) */
  function setMotherId(IStore _store, bytes32 catId, bytes32 motherId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = catId;

    _store.setField(_tableId, _keyTuple, 2, abi.encodePacked((motherId)));
  }

  /** Get hobbyId */
  function getHobbyId(bytes32 catId) internal view returns (bytes32 hobbyId) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = catId;

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 3);
    return (Bytes.slice32(_blob, 0));
  }

  /** Get hobbyId (using the specified store) */
  function getHobbyId(IStore _store, bytes32 catId) internal view returns (bytes32 hobbyId) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = catId;

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 3);
    return (Bytes.slice32(_blob, 0));
  }

  /** Set hobbyId */
  function setHobbyId(bytes32 catId, bytes32 hobbyId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = catId;

    StoreSwitch.setField(_tableId, _keyTuple, 3, abi.encodePacked((hobbyId)));
  }

  /** Set hobbyId (using the specified store) */
  function setHobbyId(IStore _store, bytes32 catId, bytes32 hobbyId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = catId;

    _store.setField(_tableId, _keyTuple, 3, abi.encodePacked((hobbyId)));
  }

  /** Get personality */
  function getPersonality(bytes32 catId) internal view returns (uint256 personality) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = catId;

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 4);
    return (uint256(Bytes.slice32(_blob, 0)));
  }

  /** Get personality (using the specified store) */
  function getPersonality(IStore _store, bytes32 catId) internal view returns (uint256 personality) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = catId;

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 4);
    return (uint256(Bytes.slice32(_blob, 0)));
  }

  /** Set personality */
  function setPersonality(bytes32 catId, uint256 personality) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = catId;

    StoreSwitch.setField(_tableId, _keyTuple, 4, abi.encodePacked((personality)));
  }

  /** Set personality (using the specified store) */
  function setPersonality(IStore _store, bytes32 catId, uint256 personality) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = catId;

    _store.setField(_tableId, _keyTuple, 4, abi.encodePacked((personality)));
  }

  /** Get skin */
  function getSkin(bytes32 catId) internal view returns (uint256 skin) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = catId;

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 5);
    return (uint256(Bytes.slice32(_blob, 0)));
  }

  /** Get skin (using the specified store) */
  function getSkin(IStore _store, bytes32 catId) internal view returns (uint256 skin) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = catId;

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 5);
    return (uint256(Bytes.slice32(_blob, 0)));
  }

  /** Set skin */
  function setSkin(bytes32 catId, uint256 skin) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = catId;

    StoreSwitch.setField(_tableId, _keyTuple, 5, abi.encodePacked((skin)));
  }

  /** Set skin (using the specified store) */
  function setSkin(IStore _store, bytes32 catId, uint256 skin) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = catId;

    _store.setField(_tableId, _keyTuple, 5, abi.encodePacked((skin)));
  }

  /** Get birthTime */
  function getBirthTime(bytes32 catId) internal view returns (uint256 birthTime) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = catId;

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 6);
    return (uint256(Bytes.slice32(_blob, 0)));
  }

  /** Get birthTime (using the specified store) */
  function getBirthTime(IStore _store, bytes32 catId) internal view returns (uint256 birthTime) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = catId;

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 6);
    return (uint256(Bytes.slice32(_blob, 0)));
  }

  /** Set birthTime */
  function setBirthTime(bytes32 catId, uint256 birthTime) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = catId;

    StoreSwitch.setField(_tableId, _keyTuple, 6, abi.encodePacked((birthTime)));
  }

  /** Set birthTime (using the specified store) */
  function setBirthTime(IStore _store, bytes32 catId, uint256 birthTime) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = catId;

    _store.setField(_tableId, _keyTuple, 6, abi.encodePacked((birthTime)));
  }

  /** Get the full data */
  function get(bytes32 catId) internal view returns (CatAttributesData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = catId;

    bytes memory _blob = StoreSwitch.getRecord(_tableId, _keyTuple, getSchema());
    return decode(_blob);
  }

  /** Get the full data (using the specified store) */
  function get(IStore _store, bytes32 catId) internal view returns (CatAttributesData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = catId;

    bytes memory _blob = _store.getRecord(_tableId, _keyTuple, getSchema());
    return decode(_blob);
  }

  /** Set the full data using individual values */
  function set(
    bytes32 catId,
    bool sex,
    bytes32 fatherId,
    bytes32 motherId,
    bytes32 hobbyId,
    uint256 personality,
    uint256 skin,
    uint256 birthTime
  ) internal {
    bytes memory _data = encode(sex, fatherId, motherId, hobbyId, personality, skin, birthTime);

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = catId;

    StoreSwitch.setRecord(_tableId, _keyTuple, _data);
  }

  /** Set the full data using individual values (using the specified store) */
  function set(
    IStore _store,
    bytes32 catId,
    bool sex,
    bytes32 fatherId,
    bytes32 motherId,
    bytes32 hobbyId,
    uint256 personality,
    uint256 skin,
    uint256 birthTime
  ) internal {
    bytes memory _data = encode(sex, fatherId, motherId, hobbyId, personality, skin, birthTime);

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = catId;

    _store.setRecord(_tableId, _keyTuple, _data);
  }

  /** Set the full data using the data struct */
  function set(bytes32 catId, CatAttributesData memory _table) internal {
    set(
      catId,
      _table.sex,
      _table.fatherId,
      _table.motherId,
      _table.hobbyId,
      _table.personality,
      _table.skin,
      _table.birthTime
    );
  }

  /** Set the full data using the data struct (using the specified store) */
  function set(IStore _store, bytes32 catId, CatAttributesData memory _table) internal {
    set(
      _store,
      catId,
      _table.sex,
      _table.fatherId,
      _table.motherId,
      _table.hobbyId,
      _table.personality,
      _table.skin,
      _table.birthTime
    );
  }

  /** Decode the tightly packed blob using this table's schema */
  function decode(bytes memory _blob) internal pure returns (CatAttributesData memory _table) {
    _table.sex = (_toBool(uint8(Bytes.slice1(_blob, 0))));

    _table.fatherId = (Bytes.slice32(_blob, 1));

    _table.motherId = (Bytes.slice32(_blob, 33));

    _table.hobbyId = (Bytes.slice32(_blob, 65));

    _table.personality = (uint256(Bytes.slice32(_blob, 97)));

    _table.skin = (uint256(Bytes.slice32(_blob, 129)));

    _table.birthTime = (uint256(Bytes.slice32(_blob, 161)));
  }

  /** Tightly pack full data using this table's schema */
  function encode(
    bool sex,
    bytes32 fatherId,
    bytes32 motherId,
    bytes32 hobbyId,
    uint256 personality,
    uint256 skin,
    uint256 birthTime
  ) internal view returns (bytes memory) {
    return abi.encodePacked(sex, fatherId, motherId, hobbyId, personality, skin, birthTime);
  }

  /** Encode keys as a bytes32 array using this table's schema */
  function encodeKeyTuple(bytes32 catId) internal pure returns (bytes32[] memory _keyTuple) {
    _keyTuple = new bytes32[](1);
    _keyTuple[0] = catId;
  }

  /* Delete all data for given keys */
  function deleteRecord(bytes32 catId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = catId;

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /* Delete all data for given keys (using the specified store) */
  function deleteRecord(IStore _store, bytes32 catId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = catId;

    _store.deleteRecord(_tableId, _keyTuple);
  }
}

function _toBool(uint8 value) pure returns (bool result) {
  assembly {
    result := value
  }
}
