// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

// Import schema type
import { SchemaType } from "@latticexyz/schema-type/src/solidity/SchemaType.sol";

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { Schema, SchemaLib } from "@latticexyz/store/src/Schema.sol";
import { PackedCounter, PackedCounterLib } from "@latticexyz/store/src/PackedCounter.sol";

bytes32 constant _tableId = bytes32(abi.encodePacked(bytes16(""), bytes16("CatFriendshipLev")));
bytes32 constant CatFriendshipLevelConfigTableId = _tableId;

struct CatFriendshipLevelConfigData {
  uint32 expLimit;
  uint256 starvingTimeLimit;
}

library CatFriendshipLevelConfig {
  /** Get the table's schema */
  function getSchema() internal pure returns (Schema) {
    SchemaType[] memory _schema = new SchemaType[](2);
    _schema[0] = SchemaType.UINT32;
    _schema[1] = SchemaType.UINT256;

    return SchemaLib.encode(_schema);
  }

  function getKeySchema() internal pure returns (Schema) {
    SchemaType[] memory _schema = new SchemaType[](1);
    _schema[0] = SchemaType.UINT32;

    return SchemaLib.encode(_schema);
  }

  /** Get the table's metadata */
  function getMetadata() internal pure returns (string memory, string[] memory) {
    string[] memory _fieldNames = new string[](2);
    _fieldNames[0] = "expLimit";
    _fieldNames[1] = "starvingTimeLimit";
    return ("CatFriendshipLevelConfig", _fieldNames);
  }

  /** Register the table's schema */
  function registerSchema() internal {
    StoreSwitch.registerSchema(_tableId, getSchema(), getKeySchema());
  }

  /** Register the table's schema (using the specified store) */
  function registerSchema(IStore _store) internal {
    _store.registerSchema(_tableId, getSchema(), getKeySchema());
  }

  /** Set the table's metadata */
  function setMetadata() internal {
    (string memory _tableName, string[] memory _fieldNames) = getMetadata();
    StoreSwitch.setMetadata(_tableId, _tableName, _fieldNames);
  }

  /** Set the table's metadata (using the specified store) */
  function setMetadata(IStore _store) internal {
    (string memory _tableName, string[] memory _fieldNames) = getMetadata();
    _store.setMetadata(_tableId, _tableName, _fieldNames);
  }

  /** Get expLimit */
  function getExpLimit(uint32 friendshipLevel) internal view returns (uint32 expLimit) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(friendshipLevel));

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 0);
    return (uint32(Bytes.slice4(_blob, 0)));
  }

  /** Get expLimit (using the specified store) */
  function getExpLimit(IStore _store, uint32 friendshipLevel) internal view returns (uint32 expLimit) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(friendshipLevel));

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 0);
    return (uint32(Bytes.slice4(_blob, 0)));
  }

  /** Set expLimit */
  function setExpLimit(uint32 friendshipLevel, uint32 expLimit) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(friendshipLevel));

    StoreSwitch.setField(_tableId, _keyTuple, 0, abi.encodePacked((expLimit)));
  }

  /** Set expLimit (using the specified store) */
  function setExpLimit(IStore _store, uint32 friendshipLevel, uint32 expLimit) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(friendshipLevel));

    _store.setField(_tableId, _keyTuple, 0, abi.encodePacked((expLimit)));
  }

  /** Get starvingTimeLimit */
  function getStarvingTimeLimit(uint32 friendshipLevel) internal view returns (uint256 starvingTimeLimit) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(friendshipLevel));

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 1);
    return (uint256(Bytes.slice32(_blob, 0)));
  }

  /** Get starvingTimeLimit (using the specified store) */
  function getStarvingTimeLimit(
    IStore _store,
    uint32 friendshipLevel
  ) internal view returns (uint256 starvingTimeLimit) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(friendshipLevel));

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 1);
    return (uint256(Bytes.slice32(_blob, 0)));
  }

  /** Set starvingTimeLimit */
  function setStarvingTimeLimit(uint32 friendshipLevel, uint256 starvingTimeLimit) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(friendshipLevel));

    StoreSwitch.setField(_tableId, _keyTuple, 1, abi.encodePacked((starvingTimeLimit)));
  }

  /** Set starvingTimeLimit (using the specified store) */
  function setStarvingTimeLimit(IStore _store, uint32 friendshipLevel, uint256 starvingTimeLimit) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(friendshipLevel));

    _store.setField(_tableId, _keyTuple, 1, abi.encodePacked((starvingTimeLimit)));
  }

  /** Get the full data */
  function get(uint32 friendshipLevel) internal view returns (CatFriendshipLevelConfigData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(friendshipLevel));

    bytes memory _blob = StoreSwitch.getRecord(_tableId, _keyTuple, getSchema());
    return decode(_blob);
  }

  /** Get the full data (using the specified store) */
  function get(
    IStore _store,
    uint32 friendshipLevel
  ) internal view returns (CatFriendshipLevelConfigData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(friendshipLevel));

    bytes memory _blob = _store.getRecord(_tableId, _keyTuple, getSchema());
    return decode(_blob);
  }

  /** Set the full data using individual values */
  function set(uint32 friendshipLevel, uint32 expLimit, uint256 starvingTimeLimit) internal {
    bytes memory _data = encode(expLimit, starvingTimeLimit);

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(friendshipLevel));

    StoreSwitch.setRecord(_tableId, _keyTuple, _data);
  }

  /** Set the full data using individual values (using the specified store) */
  function set(IStore _store, uint32 friendshipLevel, uint32 expLimit, uint256 starvingTimeLimit) internal {
    bytes memory _data = encode(expLimit, starvingTimeLimit);

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(friendshipLevel));

    _store.setRecord(_tableId, _keyTuple, _data);
  }

  /** Set the full data using the data struct */
  function set(uint32 friendshipLevel, CatFriendshipLevelConfigData memory _table) internal {
    set(friendshipLevel, _table.expLimit, _table.starvingTimeLimit);
  }

  /** Set the full data using the data struct (using the specified store) */
  function set(IStore _store, uint32 friendshipLevel, CatFriendshipLevelConfigData memory _table) internal {
    set(_store, friendshipLevel, _table.expLimit, _table.starvingTimeLimit);
  }

  /** Decode the tightly packed blob using this table's schema */
  function decode(bytes memory _blob) internal pure returns (CatFriendshipLevelConfigData memory _table) {
    _table.expLimit = (uint32(Bytes.slice4(_blob, 0)));

    _table.starvingTimeLimit = (uint256(Bytes.slice32(_blob, 4)));
  }

  /** Tightly pack full data using this table's schema */
  function encode(uint32 expLimit, uint256 starvingTimeLimit) internal view returns (bytes memory) {
    return abi.encodePacked(expLimit, starvingTimeLimit);
  }

  /** Encode keys as a bytes32 array using this table's schema */
  function encodeKeyTuple(uint32 friendshipLevel) internal pure returns (bytes32[] memory _keyTuple) {
    _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(friendshipLevel));
  }

  /* Delete all data for given keys */
  function deleteRecord(uint32 friendshipLevel) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(friendshipLevel));

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /* Delete all data for given keys (using the specified store) */
  function deleteRecord(IStore _store, uint32 friendshipLevel) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(friendshipLevel));

    _store.deleteRecord(_tableId, _keyTuple);
  }
}
