// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

// Import schema type
import { SchemaType } from "@latticexyz/schema-type/src/solidity/SchemaType.sol";

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { Schema, SchemaLib } from "@latticexyz/store/src/Schema.sol";
import { PackedCounter, PackedCounterLib } from "@latticexyz/store/src/PackedCounter.sol";

bytes32 constant _tableId = bytes32(abi.encodePacked(bytes16(""), bytes16("Cats")));
bytes32 constant CatsTableId = _tableId;

struct CatsData {
  bool sex;
  uint256 fatherId;
  uint256 motherId;
  uint256 personality;
  uint256 skin;
  uint32 exp;
  uint32 level;
  uint32 hunger;
  uint32 fun;
  uint32 health;
  uint8 cleanLevel;
  uint256 birthTime;
}

library Cats {
  /** Get the table's schema */
  function getSchema() internal pure returns (Schema) {
    SchemaType[] memory _schema = new SchemaType[](12);
    _schema[0] = SchemaType.BOOL;
    _schema[1] = SchemaType.UINT256;
    _schema[2] = SchemaType.UINT256;
    _schema[3] = SchemaType.UINT256;
    _schema[4] = SchemaType.UINT256;
    _schema[5] = SchemaType.UINT32;
    _schema[6] = SchemaType.UINT32;
    _schema[7] = SchemaType.UINT32;
    _schema[8] = SchemaType.UINT32;
    _schema[9] = SchemaType.UINT32;
    _schema[10] = SchemaType.UINT8;
    _schema[11] = SchemaType.UINT256;

    return SchemaLib.encode(_schema);
  }

  function getKeySchema() internal pure returns (Schema) {
    SchemaType[] memory _schema = new SchemaType[](1);
    _schema[0] = SchemaType.BYTES32;

    return SchemaLib.encode(_schema);
  }

  /** Get the table's metadata */
  function getMetadata() internal pure returns (string memory, string[] memory) {
    string[] memory _fieldNames = new string[](12);
    _fieldNames[0] = "sex";
    _fieldNames[1] = "fatherId";
    _fieldNames[2] = "motherId";
    _fieldNames[3] = "personality";
    _fieldNames[4] = "skin";
    _fieldNames[5] = "exp";
    _fieldNames[6] = "level";
    _fieldNames[7] = "hunger";
    _fieldNames[8] = "fun";
    _fieldNames[9] = "health";
    _fieldNames[10] = "cleanLevel";
    _fieldNames[11] = "birthTime";
    return ("Cats", _fieldNames);
  }

  /** Register the table's schema */
  function registerSchema() internal {
    StoreSwitch.registerSchema(_tableId, getSchema(), getKeySchema());
  }

  /** Register the table's schema (using the specified store) */
  function registerSchema(IStore _store) internal {
    _store.registerSchema(_tableId, getSchema(), getKeySchema());
  }

  /** Set the table's metadata */
  function setMetadata() internal {
    (string memory _tableName, string[] memory _fieldNames) = getMetadata();
    StoreSwitch.setMetadata(_tableId, _tableName, _fieldNames);
  }

  /** Set the table's metadata (using the specified store) */
  function setMetadata(IStore _store) internal {
    (string memory _tableName, string[] memory _fieldNames) = getMetadata();
    _store.setMetadata(_tableId, _tableName, _fieldNames);
  }

  /** Get sex */
  function getSex(bytes32 cat_id) internal view returns (bool sex) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = cat_id;

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 0);
    return (_toBool(uint8(Bytes.slice1(_blob, 0))));
  }

  /** Get sex (using the specified store) */
  function getSex(IStore _store, bytes32 cat_id) internal view returns (bool sex) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = cat_id;

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 0);
    return (_toBool(uint8(Bytes.slice1(_blob, 0))));
  }

  /** Set sex */
  function setSex(bytes32 cat_id, bool sex) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = cat_id;

    StoreSwitch.setField(_tableId, _keyTuple, 0, abi.encodePacked((sex)));
  }

  /** Set sex (using the specified store) */
  function setSex(IStore _store, bytes32 cat_id, bool sex) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = cat_id;

    _store.setField(_tableId, _keyTuple, 0, abi.encodePacked((sex)));
  }

  /** Get fatherId */
  function getFatherId(bytes32 cat_id) internal view returns (uint256 fatherId) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = cat_id;

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 1);
    return (uint256(Bytes.slice32(_blob, 0)));
  }

  /** Get fatherId (using the specified store) */
  function getFatherId(IStore _store, bytes32 cat_id) internal view returns (uint256 fatherId) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = cat_id;

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 1);
    return (uint256(Bytes.slice32(_blob, 0)));
  }

  /** Set fatherId */
  function setFatherId(bytes32 cat_id, uint256 fatherId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = cat_id;

    StoreSwitch.setField(_tableId, _keyTuple, 1, abi.encodePacked((fatherId)));
  }

  /** Set fatherId (using the specified store) */
  function setFatherId(IStore _store, bytes32 cat_id, uint256 fatherId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = cat_id;

    _store.setField(_tableId, _keyTuple, 1, abi.encodePacked((fatherId)));
  }

  /** Get motherId */
  function getMotherId(bytes32 cat_id) internal view returns (uint256 motherId) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = cat_id;

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 2);
    return (uint256(Bytes.slice32(_blob, 0)));
  }

  /** Get motherId (using the specified store) */
  function getMotherId(IStore _store, bytes32 cat_id) internal view returns (uint256 motherId) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = cat_id;

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 2);
    return (uint256(Bytes.slice32(_blob, 0)));
  }

  /** Set motherId */
  function setMotherId(bytes32 cat_id, uint256 motherId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = cat_id;

    StoreSwitch.setField(_tableId, _keyTuple, 2, abi.encodePacked((motherId)));
  }

  /** Set motherId (using the specified store) */
  function setMotherId(IStore _store, bytes32 cat_id, uint256 motherId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = cat_id;

    _store.setField(_tableId, _keyTuple, 2, abi.encodePacked((motherId)));
  }

  /** Get personality */
  function getPersonality(bytes32 cat_id) internal view returns (uint256 personality) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = cat_id;

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 3);
    return (uint256(Bytes.slice32(_blob, 0)));
  }

  /** Get personality (using the specified store) */
  function getPersonality(IStore _store, bytes32 cat_id) internal view returns (uint256 personality) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = cat_id;

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 3);
    return (uint256(Bytes.slice32(_blob, 0)));
  }

  /** Set personality */
  function setPersonality(bytes32 cat_id, uint256 personality) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = cat_id;

    StoreSwitch.setField(_tableId, _keyTuple, 3, abi.encodePacked((personality)));
  }

  /** Set personality (using the specified store) */
  function setPersonality(IStore _store, bytes32 cat_id, uint256 personality) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = cat_id;

    _store.setField(_tableId, _keyTuple, 3, abi.encodePacked((personality)));
  }

  /** Get skin */
  function getSkin(bytes32 cat_id) internal view returns (uint256 skin) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = cat_id;

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 4);
    return (uint256(Bytes.slice32(_blob, 0)));
  }

  /** Get skin (using the specified store) */
  function getSkin(IStore _store, bytes32 cat_id) internal view returns (uint256 skin) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = cat_id;

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 4);
    return (uint256(Bytes.slice32(_blob, 0)));
  }

  /** Set skin */
  function setSkin(bytes32 cat_id, uint256 skin) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = cat_id;

    StoreSwitch.setField(_tableId, _keyTuple, 4, abi.encodePacked((skin)));
  }

  /** Set skin (using the specified store) */
  function setSkin(IStore _store, bytes32 cat_id, uint256 skin) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = cat_id;

    _store.setField(_tableId, _keyTuple, 4, abi.encodePacked((skin)));
  }

  /** Get exp */
  function getExp(bytes32 cat_id) internal view returns (uint32 exp) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = cat_id;

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 5);
    return (uint32(Bytes.slice4(_blob, 0)));
  }

  /** Get exp (using the specified store) */
  function getExp(IStore _store, bytes32 cat_id) internal view returns (uint32 exp) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = cat_id;

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 5);
    return (uint32(Bytes.slice4(_blob, 0)));
  }

  /** Set exp */
  function setExp(bytes32 cat_id, uint32 exp) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = cat_id;

    StoreSwitch.setField(_tableId, _keyTuple, 5, abi.encodePacked((exp)));
  }

  /** Set exp (using the specified store) */
  function setExp(IStore _store, bytes32 cat_id, uint32 exp) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = cat_id;

    _store.setField(_tableId, _keyTuple, 5, abi.encodePacked((exp)));
  }

  /** Get level */
  function getLevel(bytes32 cat_id) internal view returns (uint32 level) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = cat_id;

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 6);
    return (uint32(Bytes.slice4(_blob, 0)));
  }

  /** Get level (using the specified store) */
  function getLevel(IStore _store, bytes32 cat_id) internal view returns (uint32 level) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = cat_id;

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 6);
    return (uint32(Bytes.slice4(_blob, 0)));
  }

  /** Set level */
  function setLevel(bytes32 cat_id, uint32 level) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = cat_id;

    StoreSwitch.setField(_tableId, _keyTuple, 6, abi.encodePacked((level)));
  }

  /** Set level (using the specified store) */
  function setLevel(IStore _store, bytes32 cat_id, uint32 level) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = cat_id;

    _store.setField(_tableId, _keyTuple, 6, abi.encodePacked((level)));
  }

  /** Get hunger */
  function getHunger(bytes32 cat_id) internal view returns (uint32 hunger) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = cat_id;

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 7);
    return (uint32(Bytes.slice4(_blob, 0)));
  }

  /** Get hunger (using the specified store) */
  function getHunger(IStore _store, bytes32 cat_id) internal view returns (uint32 hunger) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = cat_id;

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 7);
    return (uint32(Bytes.slice4(_blob, 0)));
  }

  /** Set hunger */
  function setHunger(bytes32 cat_id, uint32 hunger) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = cat_id;

    StoreSwitch.setField(_tableId, _keyTuple, 7, abi.encodePacked((hunger)));
  }

  /** Set hunger (using the specified store) */
  function setHunger(IStore _store, bytes32 cat_id, uint32 hunger) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = cat_id;

    _store.setField(_tableId, _keyTuple, 7, abi.encodePacked((hunger)));
  }

  /** Get fun */
  function getFun(bytes32 cat_id) internal view returns (uint32 fun) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = cat_id;

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 8);
    return (uint32(Bytes.slice4(_blob, 0)));
  }

  /** Get fun (using the specified store) */
  function getFun(IStore _store, bytes32 cat_id) internal view returns (uint32 fun) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = cat_id;

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 8);
    return (uint32(Bytes.slice4(_blob, 0)));
  }

  /** Set fun */
  function setFun(bytes32 cat_id, uint32 fun) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = cat_id;

    StoreSwitch.setField(_tableId, _keyTuple, 8, abi.encodePacked((fun)));
  }

  /** Set fun (using the specified store) */
  function setFun(IStore _store, bytes32 cat_id, uint32 fun) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = cat_id;

    _store.setField(_tableId, _keyTuple, 8, abi.encodePacked((fun)));
  }

  /** Get health */
  function getHealth(bytes32 cat_id) internal view returns (uint32 health) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = cat_id;

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 9);
    return (uint32(Bytes.slice4(_blob, 0)));
  }

  /** Get health (using the specified store) */
  function getHealth(IStore _store, bytes32 cat_id) internal view returns (uint32 health) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = cat_id;

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 9);
    return (uint32(Bytes.slice4(_blob, 0)));
  }

  /** Set health */
  function setHealth(bytes32 cat_id, uint32 health) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = cat_id;

    StoreSwitch.setField(_tableId, _keyTuple, 9, abi.encodePacked((health)));
  }

  /** Set health (using the specified store) */
  function setHealth(IStore _store, bytes32 cat_id, uint32 health) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = cat_id;

    _store.setField(_tableId, _keyTuple, 9, abi.encodePacked((health)));
  }

  /** Get cleanLevel */
  function getCleanLevel(bytes32 cat_id) internal view returns (uint8 cleanLevel) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = cat_id;

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 10);
    return (uint8(Bytes.slice1(_blob, 0)));
  }

  /** Get cleanLevel (using the specified store) */
  function getCleanLevel(IStore _store, bytes32 cat_id) internal view returns (uint8 cleanLevel) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = cat_id;

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 10);
    return (uint8(Bytes.slice1(_blob, 0)));
  }

  /** Set cleanLevel */
  function setCleanLevel(bytes32 cat_id, uint8 cleanLevel) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = cat_id;

    StoreSwitch.setField(_tableId, _keyTuple, 10, abi.encodePacked((cleanLevel)));
  }

  /** Set cleanLevel (using the specified store) */
  function setCleanLevel(IStore _store, bytes32 cat_id, uint8 cleanLevel) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = cat_id;

    _store.setField(_tableId, _keyTuple, 10, abi.encodePacked((cleanLevel)));
  }

  /** Get birthTime */
  function getBirthTime(bytes32 cat_id) internal view returns (uint256 birthTime) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = cat_id;

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 11);
    return (uint256(Bytes.slice32(_blob, 0)));
  }

  /** Get birthTime (using the specified store) */
  function getBirthTime(IStore _store, bytes32 cat_id) internal view returns (uint256 birthTime) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = cat_id;

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 11);
    return (uint256(Bytes.slice32(_blob, 0)));
  }

  /** Set birthTime */
  function setBirthTime(bytes32 cat_id, uint256 birthTime) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = cat_id;

    StoreSwitch.setField(_tableId, _keyTuple, 11, abi.encodePacked((birthTime)));
  }

  /** Set birthTime (using the specified store) */
  function setBirthTime(IStore _store, bytes32 cat_id, uint256 birthTime) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = cat_id;

    _store.setField(_tableId, _keyTuple, 11, abi.encodePacked((birthTime)));
  }

  /** Get the full data */
  function get(bytes32 cat_id) internal view returns (CatsData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = cat_id;

    bytes memory _blob = StoreSwitch.getRecord(_tableId, _keyTuple, getSchema());
    return decode(_blob);
  }

  /** Get the full data (using the specified store) */
  function get(IStore _store, bytes32 cat_id) internal view returns (CatsData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = cat_id;

    bytes memory _blob = _store.getRecord(_tableId, _keyTuple, getSchema());
    return decode(_blob);
  }

  /** Set the full data using individual values */
  function set(
    bytes32 cat_id,
    bool sex,
    uint256 fatherId,
    uint256 motherId,
    uint256 personality,
    uint256 skin,
    uint32 exp,
    uint32 level,
    uint32 hunger,
    uint32 fun,
    uint32 health,
    uint8 cleanLevel,
    uint256 birthTime
  ) internal {
    bytes memory _data = encode(
      sex,
      fatherId,
      motherId,
      personality,
      skin,
      exp,
      level,
      hunger,
      fun,
      health,
      cleanLevel,
      birthTime
    );

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = cat_id;

    StoreSwitch.setRecord(_tableId, _keyTuple, _data);
  }

  /** Set the full data using individual values (using the specified store) */
  function set(
    IStore _store,
    bytes32 cat_id,
    bool sex,
    uint256 fatherId,
    uint256 motherId,
    uint256 personality,
    uint256 skin,
    uint32 exp,
    uint32 level,
    uint32 hunger,
    uint32 fun,
    uint32 health,
    uint8 cleanLevel,
    uint256 birthTime
  ) internal {
    bytes memory _data = encode(
      sex,
      fatherId,
      motherId,
      personality,
      skin,
      exp,
      level,
      hunger,
      fun,
      health,
      cleanLevel,
      birthTime
    );

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = cat_id;

    _store.setRecord(_tableId, _keyTuple, _data);
  }

  /** Set the full data using the data struct */
  function set(bytes32 cat_id, CatsData memory _table) internal {
    set(
      cat_id,
      _table.sex,
      _table.fatherId,
      _table.motherId,
      _table.personality,
      _table.skin,
      _table.exp,
      _table.level,
      _table.hunger,
      _table.fun,
      _table.health,
      _table.cleanLevel,
      _table.birthTime
    );
  }

  /** Set the full data using the data struct (using the specified store) */
  function set(IStore _store, bytes32 cat_id, CatsData memory _table) internal {
    set(
      _store,
      cat_id,
      _table.sex,
      _table.fatherId,
      _table.motherId,
      _table.personality,
      _table.skin,
      _table.exp,
      _table.level,
      _table.hunger,
      _table.fun,
      _table.health,
      _table.cleanLevel,
      _table.birthTime
    );
  }

  /** Decode the tightly packed blob using this table's schema */
  function decode(bytes memory _blob) internal pure returns (CatsData memory _table) {
    _table.sex = (_toBool(uint8(Bytes.slice1(_blob, 0))));

    _table.fatherId = (uint256(Bytes.slice32(_blob, 1)));

    _table.motherId = (uint256(Bytes.slice32(_blob, 33)));

    _table.personality = (uint256(Bytes.slice32(_blob, 65)));

    _table.skin = (uint256(Bytes.slice32(_blob, 97)));

    _table.exp = (uint32(Bytes.slice4(_blob, 129)));

    _table.level = (uint32(Bytes.slice4(_blob, 133)));

    _table.hunger = (uint32(Bytes.slice4(_blob, 137)));

    _table.fun = (uint32(Bytes.slice4(_blob, 141)));

    _table.health = (uint32(Bytes.slice4(_blob, 145)));

    _table.cleanLevel = (uint8(Bytes.slice1(_blob, 149)));

    _table.birthTime = (uint256(Bytes.slice32(_blob, 150)));
  }

  /** Tightly pack full data using this table's schema */
  function encode(
    bool sex,
    uint256 fatherId,
    uint256 motherId,
    uint256 personality,
    uint256 skin,
    uint32 exp,
    uint32 level,
    uint32 hunger,
    uint32 fun,
    uint32 health,
    uint8 cleanLevel,
    uint256 birthTime
  ) internal view returns (bytes memory) {
    return
      abi.encodePacked(
        sex,
        fatherId,
        motherId,
        personality,
        skin,
        exp,
        level,
        hunger,
        fun,
        health,
        cleanLevel,
        birthTime
      );
  }

  /** Encode keys as a bytes32 array using this table's schema */
  function encodeKeyTuple(bytes32 cat_id) internal pure returns (bytes32[] memory _keyTuple) {
    _keyTuple = new bytes32[](1);
    _keyTuple[0] = cat_id;
  }

  /* Delete all data for given keys */
  function deleteRecord(bytes32 cat_id) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = cat_id;

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /* Delete all data for given keys (using the specified store) */
  function deleteRecord(IStore _store, bytes32 cat_id) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = cat_id;

    _store.deleteRecord(_tableId, _keyTuple);
  }
}

function _toBool(uint8 value) pure returns (bool result) {
  assembly {
    result := value
  }
}
