// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

// Import schema type
import { SchemaType } from "@latticexyz/schema-type/src/solidity/SchemaType.sol";

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { Schema, SchemaLib } from "@latticexyz/store/src/Schema.sol";
import { PackedCounter, PackedCounterLib } from "@latticexyz/store/src/PackedCounter.sol";

bytes32 constant _tableId = bytes32(abi.encodePacked(bytes16(""), bytes16("Shop")));
bytes32 constant ShopTableId = _tableId;

struct ShopData {
  uint256 itemCoinPrice;
  uint256 itemDiamondPrice;
  uint256 itemTokenPrice;
  uint32 itemUnlockExp;
  uint32 itemDailyBuyLimit;
  uint32 itemWeeklyBuyLimit;
  uint32 itemMonthlyBuyLimit;
  uint32 itemForeverBuyLimit;
}

library Shop {
  /** Get the table's schema */
  function getSchema() internal pure returns (Schema) {
    SchemaType[] memory _schema = new SchemaType[](8);
    _schema[0] = SchemaType.UINT256;
    _schema[1] = SchemaType.UINT256;
    _schema[2] = SchemaType.UINT256;
    _schema[3] = SchemaType.UINT32;
    _schema[4] = SchemaType.UINT32;
    _schema[5] = SchemaType.UINT32;
    _schema[6] = SchemaType.UINT32;
    _schema[7] = SchemaType.UINT32;

    return SchemaLib.encode(_schema);
  }

  function getKeySchema() internal pure returns (Schema) {
    SchemaType[] memory _schema = new SchemaType[](1);
    _schema[0] = SchemaType.UINT256;

    return SchemaLib.encode(_schema);
  }

  /** Get the table's metadata */
  function getMetadata() internal pure returns (string memory, string[] memory) {
    string[] memory _fieldNames = new string[](8);
    _fieldNames[0] = "itemCoinPrice";
    _fieldNames[1] = "itemDiamondPrice";
    _fieldNames[2] = "itemTokenPrice";
    _fieldNames[3] = "itemUnlockExp";
    _fieldNames[4] = "itemDailyBuyLimit";
    _fieldNames[5] = "itemWeeklyBuyLimit";
    _fieldNames[6] = "itemMonthlyBuyLimit";
    _fieldNames[7] = "itemForeverBuyLimit";
    return ("Shop", _fieldNames);
  }

  /** Register the table's schema */
  function registerSchema() internal {
    StoreSwitch.registerSchema(_tableId, getSchema(), getKeySchema());
  }

  /** Register the table's schema (using the specified store) */
  function registerSchema(IStore _store) internal {
    _store.registerSchema(_tableId, getSchema(), getKeySchema());
  }

  /** Set the table's metadata */
  function setMetadata() internal {
    (string memory _tableName, string[] memory _fieldNames) = getMetadata();
    StoreSwitch.setMetadata(_tableId, _tableName, _fieldNames);
  }

  /** Set the table's metadata (using the specified store) */
  function setMetadata(IStore _store) internal {
    (string memory _tableName, string[] memory _fieldNames) = getMetadata();
    _store.setMetadata(_tableId, _tableName, _fieldNames);
  }

  /** Get itemCoinPrice */
  function getItemCoinPrice(uint256 itemId) internal view returns (uint256 itemCoinPrice) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 0);
    return (uint256(Bytes.slice32(_blob, 0)));
  }

  /** Get itemCoinPrice (using the specified store) */
  function getItemCoinPrice(IStore _store, uint256 itemId) internal view returns (uint256 itemCoinPrice) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 0);
    return (uint256(Bytes.slice32(_blob, 0)));
  }

  /** Set itemCoinPrice */
  function setItemCoinPrice(uint256 itemId, uint256 itemCoinPrice) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    StoreSwitch.setField(_tableId, _keyTuple, 0, abi.encodePacked((itemCoinPrice)));
  }

  /** Set itemCoinPrice (using the specified store) */
  function setItemCoinPrice(IStore _store, uint256 itemId, uint256 itemCoinPrice) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    _store.setField(_tableId, _keyTuple, 0, abi.encodePacked((itemCoinPrice)));
  }

  /** Get itemDiamondPrice */
  function getItemDiamondPrice(uint256 itemId) internal view returns (uint256 itemDiamondPrice) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 1);
    return (uint256(Bytes.slice32(_blob, 0)));
  }

  /** Get itemDiamondPrice (using the specified store) */
  function getItemDiamondPrice(IStore _store, uint256 itemId) internal view returns (uint256 itemDiamondPrice) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 1);
    return (uint256(Bytes.slice32(_blob, 0)));
  }

  /** Set itemDiamondPrice */
  function setItemDiamondPrice(uint256 itemId, uint256 itemDiamondPrice) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    StoreSwitch.setField(_tableId, _keyTuple, 1, abi.encodePacked((itemDiamondPrice)));
  }

  /** Set itemDiamondPrice (using the specified store) */
  function setItemDiamondPrice(IStore _store, uint256 itemId, uint256 itemDiamondPrice) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    _store.setField(_tableId, _keyTuple, 1, abi.encodePacked((itemDiamondPrice)));
  }

  /** Get itemTokenPrice */
  function getItemTokenPrice(uint256 itemId) internal view returns (uint256 itemTokenPrice) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 2);
    return (uint256(Bytes.slice32(_blob, 0)));
  }

  /** Get itemTokenPrice (using the specified store) */
  function getItemTokenPrice(IStore _store, uint256 itemId) internal view returns (uint256 itemTokenPrice) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 2);
    return (uint256(Bytes.slice32(_blob, 0)));
  }

  /** Set itemTokenPrice */
  function setItemTokenPrice(uint256 itemId, uint256 itemTokenPrice) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    StoreSwitch.setField(_tableId, _keyTuple, 2, abi.encodePacked((itemTokenPrice)));
  }

  /** Set itemTokenPrice (using the specified store) */
  function setItemTokenPrice(IStore _store, uint256 itemId, uint256 itemTokenPrice) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    _store.setField(_tableId, _keyTuple, 2, abi.encodePacked((itemTokenPrice)));
  }

  /** Get itemUnlockExp */
  function getItemUnlockExp(uint256 itemId) internal view returns (uint32 itemUnlockExp) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 3);
    return (uint32(Bytes.slice4(_blob, 0)));
  }

  /** Get itemUnlockExp (using the specified store) */
  function getItemUnlockExp(IStore _store, uint256 itemId) internal view returns (uint32 itemUnlockExp) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 3);
    return (uint32(Bytes.slice4(_blob, 0)));
  }

  /** Set itemUnlockExp */
  function setItemUnlockExp(uint256 itemId, uint32 itemUnlockExp) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    StoreSwitch.setField(_tableId, _keyTuple, 3, abi.encodePacked((itemUnlockExp)));
  }

  /** Set itemUnlockExp (using the specified store) */
  function setItemUnlockExp(IStore _store, uint256 itemId, uint32 itemUnlockExp) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    _store.setField(_tableId, _keyTuple, 3, abi.encodePacked((itemUnlockExp)));
  }

  /** Get itemDailyBuyLimit */
  function getItemDailyBuyLimit(uint256 itemId) internal view returns (uint32 itemDailyBuyLimit) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 4);
    return (uint32(Bytes.slice4(_blob, 0)));
  }

  /** Get itemDailyBuyLimit (using the specified store) */
  function getItemDailyBuyLimit(IStore _store, uint256 itemId) internal view returns (uint32 itemDailyBuyLimit) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 4);
    return (uint32(Bytes.slice4(_blob, 0)));
  }

  /** Set itemDailyBuyLimit */
  function setItemDailyBuyLimit(uint256 itemId, uint32 itemDailyBuyLimit) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    StoreSwitch.setField(_tableId, _keyTuple, 4, abi.encodePacked((itemDailyBuyLimit)));
  }

  /** Set itemDailyBuyLimit (using the specified store) */
  function setItemDailyBuyLimit(IStore _store, uint256 itemId, uint32 itemDailyBuyLimit) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    _store.setField(_tableId, _keyTuple, 4, abi.encodePacked((itemDailyBuyLimit)));
  }

  /** Get itemWeeklyBuyLimit */
  function getItemWeeklyBuyLimit(uint256 itemId) internal view returns (uint32 itemWeeklyBuyLimit) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 5);
    return (uint32(Bytes.slice4(_blob, 0)));
  }

  /** Get itemWeeklyBuyLimit (using the specified store) */
  function getItemWeeklyBuyLimit(IStore _store, uint256 itemId) internal view returns (uint32 itemWeeklyBuyLimit) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 5);
    return (uint32(Bytes.slice4(_blob, 0)));
  }

  /** Set itemWeeklyBuyLimit */
  function setItemWeeklyBuyLimit(uint256 itemId, uint32 itemWeeklyBuyLimit) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    StoreSwitch.setField(_tableId, _keyTuple, 5, abi.encodePacked((itemWeeklyBuyLimit)));
  }

  /** Set itemWeeklyBuyLimit (using the specified store) */
  function setItemWeeklyBuyLimit(IStore _store, uint256 itemId, uint32 itemWeeklyBuyLimit) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    _store.setField(_tableId, _keyTuple, 5, abi.encodePacked((itemWeeklyBuyLimit)));
  }

  /** Get itemMonthlyBuyLimit */
  function getItemMonthlyBuyLimit(uint256 itemId) internal view returns (uint32 itemMonthlyBuyLimit) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 6);
    return (uint32(Bytes.slice4(_blob, 0)));
  }

  /** Get itemMonthlyBuyLimit (using the specified store) */
  function getItemMonthlyBuyLimit(IStore _store, uint256 itemId) internal view returns (uint32 itemMonthlyBuyLimit) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 6);
    return (uint32(Bytes.slice4(_blob, 0)));
  }

  /** Set itemMonthlyBuyLimit */
  function setItemMonthlyBuyLimit(uint256 itemId, uint32 itemMonthlyBuyLimit) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    StoreSwitch.setField(_tableId, _keyTuple, 6, abi.encodePacked((itemMonthlyBuyLimit)));
  }

  /** Set itemMonthlyBuyLimit (using the specified store) */
  function setItemMonthlyBuyLimit(IStore _store, uint256 itemId, uint32 itemMonthlyBuyLimit) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    _store.setField(_tableId, _keyTuple, 6, abi.encodePacked((itemMonthlyBuyLimit)));
  }

  /** Get itemForeverBuyLimit */
  function getItemForeverBuyLimit(uint256 itemId) internal view returns (uint32 itemForeverBuyLimit) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 7);
    return (uint32(Bytes.slice4(_blob, 0)));
  }

  /** Get itemForeverBuyLimit (using the specified store) */
  function getItemForeverBuyLimit(IStore _store, uint256 itemId) internal view returns (uint32 itemForeverBuyLimit) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 7);
    return (uint32(Bytes.slice4(_blob, 0)));
  }

  /** Set itemForeverBuyLimit */
  function setItemForeverBuyLimit(uint256 itemId, uint32 itemForeverBuyLimit) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    StoreSwitch.setField(_tableId, _keyTuple, 7, abi.encodePacked((itemForeverBuyLimit)));
  }

  /** Set itemForeverBuyLimit (using the specified store) */
  function setItemForeverBuyLimit(IStore _store, uint256 itemId, uint32 itemForeverBuyLimit) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    _store.setField(_tableId, _keyTuple, 7, abi.encodePacked((itemForeverBuyLimit)));
  }

  /** Get the full data */
  function get(uint256 itemId) internal view returns (ShopData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    bytes memory _blob = StoreSwitch.getRecord(_tableId, _keyTuple, getSchema());
    return decode(_blob);
  }

  /** Get the full data (using the specified store) */
  function get(IStore _store, uint256 itemId) internal view returns (ShopData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    bytes memory _blob = _store.getRecord(_tableId, _keyTuple, getSchema());
    return decode(_blob);
  }

  /** Set the full data using individual values */
  function set(
    uint256 itemId,
    uint256 itemCoinPrice,
    uint256 itemDiamondPrice,
    uint256 itemTokenPrice,
    uint32 itemUnlockExp,
    uint32 itemDailyBuyLimit,
    uint32 itemWeeklyBuyLimit,
    uint32 itemMonthlyBuyLimit,
    uint32 itemForeverBuyLimit
  ) internal {
    bytes memory _data = encode(
      itemCoinPrice,
      itemDiamondPrice,
      itemTokenPrice,
      itemUnlockExp,
      itemDailyBuyLimit,
      itemWeeklyBuyLimit,
      itemMonthlyBuyLimit,
      itemForeverBuyLimit
    );

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    StoreSwitch.setRecord(_tableId, _keyTuple, _data);
  }

  /** Set the full data using individual values (using the specified store) */
  function set(
    IStore _store,
    uint256 itemId,
    uint256 itemCoinPrice,
    uint256 itemDiamondPrice,
    uint256 itemTokenPrice,
    uint32 itemUnlockExp,
    uint32 itemDailyBuyLimit,
    uint32 itemWeeklyBuyLimit,
    uint32 itemMonthlyBuyLimit,
    uint32 itemForeverBuyLimit
  ) internal {
    bytes memory _data = encode(
      itemCoinPrice,
      itemDiamondPrice,
      itemTokenPrice,
      itemUnlockExp,
      itemDailyBuyLimit,
      itemWeeklyBuyLimit,
      itemMonthlyBuyLimit,
      itemForeverBuyLimit
    );

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    _store.setRecord(_tableId, _keyTuple, _data);
  }

  /** Set the full data using the data struct */
  function set(uint256 itemId, ShopData memory _table) internal {
    set(
      itemId,
      _table.itemCoinPrice,
      _table.itemDiamondPrice,
      _table.itemTokenPrice,
      _table.itemUnlockExp,
      _table.itemDailyBuyLimit,
      _table.itemWeeklyBuyLimit,
      _table.itemMonthlyBuyLimit,
      _table.itemForeverBuyLimit
    );
  }

  /** Set the full data using the data struct (using the specified store) */
  function set(IStore _store, uint256 itemId, ShopData memory _table) internal {
    set(
      _store,
      itemId,
      _table.itemCoinPrice,
      _table.itemDiamondPrice,
      _table.itemTokenPrice,
      _table.itemUnlockExp,
      _table.itemDailyBuyLimit,
      _table.itemWeeklyBuyLimit,
      _table.itemMonthlyBuyLimit,
      _table.itemForeverBuyLimit
    );
  }

  /** Decode the tightly packed blob using this table's schema */
  function decode(bytes memory _blob) internal pure returns (ShopData memory _table) {
    _table.itemCoinPrice = (uint256(Bytes.slice32(_blob, 0)));

    _table.itemDiamondPrice = (uint256(Bytes.slice32(_blob, 32)));

    _table.itemTokenPrice = (uint256(Bytes.slice32(_blob, 64)));

    _table.itemUnlockExp = (uint32(Bytes.slice4(_blob, 96)));

    _table.itemDailyBuyLimit = (uint32(Bytes.slice4(_blob, 100)));

    _table.itemWeeklyBuyLimit = (uint32(Bytes.slice4(_blob, 104)));

    _table.itemMonthlyBuyLimit = (uint32(Bytes.slice4(_blob, 108)));

    _table.itemForeverBuyLimit = (uint32(Bytes.slice4(_blob, 112)));
  }

  /** Tightly pack full data using this table's schema */
  function encode(
    uint256 itemCoinPrice,
    uint256 itemDiamondPrice,
    uint256 itemTokenPrice,
    uint32 itemUnlockExp,
    uint32 itemDailyBuyLimit,
    uint32 itemWeeklyBuyLimit,
    uint32 itemMonthlyBuyLimit,
    uint32 itemForeverBuyLimit
  ) internal view returns (bytes memory) {
    return
      abi.encodePacked(
        itemCoinPrice,
        itemDiamondPrice,
        itemTokenPrice,
        itemUnlockExp,
        itemDailyBuyLimit,
        itemWeeklyBuyLimit,
        itemMonthlyBuyLimit,
        itemForeverBuyLimit
      );
  }

  /** Encode keys as a bytes32 array using this table's schema */
  function encodeKeyTuple(uint256 itemId) internal pure returns (bytes32[] memory _keyTuple) {
    _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));
  }

  /* Delete all data for given keys */
  function deleteRecord(uint256 itemId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /* Delete all data for given keys (using the specified store) */
  function deleteRecord(IStore _store, uint256 itemId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(itemId));

    _store.deleteRecord(_tableId, _keyTuple);
  }
}
