// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

// Import schema type
import { SchemaType } from "@latticexyz/schema-type/src/solidity/SchemaType.sol";

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { Schema, SchemaLib } from "@latticexyz/store/src/Schema.sol";
import { PackedCounter, PackedCounterLib } from "@latticexyz/store/src/PackedCounter.sol";

bytes32 constant _tableId = bytes32(abi.encodePacked(bytes16(""), bytes16("TaskConfig")));
bytes32 constant TaskConfigTableId = _tableId;

struct TaskConfigData {
  uint32 level;
  uint32 dupPeriod;
  uint32 rewardExp;
  uint256 rewardCoins;
  uint256 rewardDiamonds;
  bool itemConsumed;
  bytes32[] itemIds;
  uint32[] itemQuantities;
  bytes32[] rewardItemIds;
  uint32[] rewardItemQuantities;
}

library TaskConfig {
  /** Get the table's schema */
  function getSchema() internal pure returns (Schema) {
    SchemaType[] memory _schema = new SchemaType[](10);
    _schema[0] = SchemaType.UINT32;
    _schema[1] = SchemaType.UINT32;
    _schema[2] = SchemaType.UINT32;
    _schema[3] = SchemaType.UINT256;
    _schema[4] = SchemaType.UINT256;
    _schema[5] = SchemaType.BOOL;
    _schema[6] = SchemaType.BYTES32_ARRAY;
    _schema[7] = SchemaType.UINT32_ARRAY;
    _schema[8] = SchemaType.BYTES32_ARRAY;
    _schema[9] = SchemaType.UINT32_ARRAY;

    return SchemaLib.encode(_schema);
  }

  function getKeySchema() internal pure returns (Schema) {
    SchemaType[] memory _schema = new SchemaType[](1);
    _schema[0] = SchemaType.BYTES32;

    return SchemaLib.encode(_schema);
  }

  /** Get the table's metadata */
  function getMetadata() internal pure returns (string memory, string[] memory) {
    string[] memory _fieldNames = new string[](10);
    _fieldNames[0] = "level";
    _fieldNames[1] = "dupPeriod";
    _fieldNames[2] = "rewardExp";
    _fieldNames[3] = "rewardCoins";
    _fieldNames[4] = "rewardDiamonds";
    _fieldNames[5] = "itemConsumed";
    _fieldNames[6] = "itemIds";
    _fieldNames[7] = "itemQuantities";
    _fieldNames[8] = "rewardItemIds";
    _fieldNames[9] = "rewardItemQuantities";
    return ("TaskConfig", _fieldNames);
  }

  /** Register the table's schema */
  function registerSchema() internal {
    StoreSwitch.registerSchema(_tableId, getSchema(), getKeySchema());
  }

  /** Register the table's schema (using the specified store) */
  function registerSchema(IStore _store) internal {
    _store.registerSchema(_tableId, getSchema(), getKeySchema());
  }

  /** Set the table's metadata */
  function setMetadata() internal {
    (string memory _tableName, string[] memory _fieldNames) = getMetadata();
    StoreSwitch.setMetadata(_tableId, _tableName, _fieldNames);
  }

  /** Set the table's metadata (using the specified store) */
  function setMetadata(IStore _store) internal {
    (string memory _tableName, string[] memory _fieldNames) = getMetadata();
    _store.setMetadata(_tableId, _tableName, _fieldNames);
  }

  /** Get level */
  function getLevel(bytes32 taskId) internal view returns (uint32 level) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 0);
    return (uint32(Bytes.slice4(_blob, 0)));
  }

  /** Get level (using the specified store) */
  function getLevel(IStore _store, bytes32 taskId) internal view returns (uint32 level) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 0);
    return (uint32(Bytes.slice4(_blob, 0)));
  }

  /** Set level */
  function setLevel(bytes32 taskId, uint32 level) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    StoreSwitch.setField(_tableId, _keyTuple, 0, abi.encodePacked((level)));
  }

  /** Set level (using the specified store) */
  function setLevel(IStore _store, bytes32 taskId, uint32 level) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    _store.setField(_tableId, _keyTuple, 0, abi.encodePacked((level)));
  }

  /** Get dupPeriod */
  function getDupPeriod(bytes32 taskId) internal view returns (uint32 dupPeriod) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 1);
    return (uint32(Bytes.slice4(_blob, 0)));
  }

  /** Get dupPeriod (using the specified store) */
  function getDupPeriod(IStore _store, bytes32 taskId) internal view returns (uint32 dupPeriod) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 1);
    return (uint32(Bytes.slice4(_blob, 0)));
  }

  /** Set dupPeriod */
  function setDupPeriod(bytes32 taskId, uint32 dupPeriod) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    StoreSwitch.setField(_tableId, _keyTuple, 1, abi.encodePacked((dupPeriod)));
  }

  /** Set dupPeriod (using the specified store) */
  function setDupPeriod(IStore _store, bytes32 taskId, uint32 dupPeriod) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    _store.setField(_tableId, _keyTuple, 1, abi.encodePacked((dupPeriod)));
  }

  /** Get rewardExp */
  function getRewardExp(bytes32 taskId) internal view returns (uint32 rewardExp) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 2);
    return (uint32(Bytes.slice4(_blob, 0)));
  }

  /** Get rewardExp (using the specified store) */
  function getRewardExp(IStore _store, bytes32 taskId) internal view returns (uint32 rewardExp) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 2);
    return (uint32(Bytes.slice4(_blob, 0)));
  }

  /** Set rewardExp */
  function setRewardExp(bytes32 taskId, uint32 rewardExp) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    StoreSwitch.setField(_tableId, _keyTuple, 2, abi.encodePacked((rewardExp)));
  }

  /** Set rewardExp (using the specified store) */
  function setRewardExp(IStore _store, bytes32 taskId, uint32 rewardExp) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    _store.setField(_tableId, _keyTuple, 2, abi.encodePacked((rewardExp)));
  }

  /** Get rewardCoins */
  function getRewardCoins(bytes32 taskId) internal view returns (uint256 rewardCoins) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 3);
    return (uint256(Bytes.slice32(_blob, 0)));
  }

  /** Get rewardCoins (using the specified store) */
  function getRewardCoins(IStore _store, bytes32 taskId) internal view returns (uint256 rewardCoins) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 3);
    return (uint256(Bytes.slice32(_blob, 0)));
  }

  /** Set rewardCoins */
  function setRewardCoins(bytes32 taskId, uint256 rewardCoins) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    StoreSwitch.setField(_tableId, _keyTuple, 3, abi.encodePacked((rewardCoins)));
  }

  /** Set rewardCoins (using the specified store) */
  function setRewardCoins(IStore _store, bytes32 taskId, uint256 rewardCoins) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    _store.setField(_tableId, _keyTuple, 3, abi.encodePacked((rewardCoins)));
  }

  /** Get rewardDiamonds */
  function getRewardDiamonds(bytes32 taskId) internal view returns (uint256 rewardDiamonds) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 4);
    return (uint256(Bytes.slice32(_blob, 0)));
  }

  /** Get rewardDiamonds (using the specified store) */
  function getRewardDiamonds(IStore _store, bytes32 taskId) internal view returns (uint256 rewardDiamonds) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 4);
    return (uint256(Bytes.slice32(_blob, 0)));
  }

  /** Set rewardDiamonds */
  function setRewardDiamonds(bytes32 taskId, uint256 rewardDiamonds) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    StoreSwitch.setField(_tableId, _keyTuple, 4, abi.encodePacked((rewardDiamonds)));
  }

  /** Set rewardDiamonds (using the specified store) */
  function setRewardDiamonds(IStore _store, bytes32 taskId, uint256 rewardDiamonds) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    _store.setField(_tableId, _keyTuple, 4, abi.encodePacked((rewardDiamonds)));
  }

  /** Get itemConsumed */
  function getItemConsumed(bytes32 taskId) internal view returns (bool itemConsumed) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 5);
    return (_toBool(uint8(Bytes.slice1(_blob, 0))));
  }

  /** Get itemConsumed (using the specified store) */
  function getItemConsumed(IStore _store, bytes32 taskId) internal view returns (bool itemConsumed) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 5);
    return (_toBool(uint8(Bytes.slice1(_blob, 0))));
  }

  /** Set itemConsumed */
  function setItemConsumed(bytes32 taskId, bool itemConsumed) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    StoreSwitch.setField(_tableId, _keyTuple, 5, abi.encodePacked((itemConsumed)));
  }

  /** Set itemConsumed (using the specified store) */
  function setItemConsumed(IStore _store, bytes32 taskId, bool itemConsumed) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    _store.setField(_tableId, _keyTuple, 5, abi.encodePacked((itemConsumed)));
  }

  /** Get itemIds */
  function getItemIds(bytes32 taskId) internal view returns (bytes32[] memory itemIds) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 6);
    return (SliceLib.getSubslice(_blob, 0, _blob.length).decodeArray_bytes32());
  }

  /** Get itemIds (using the specified store) */
  function getItemIds(IStore _store, bytes32 taskId) internal view returns (bytes32[] memory itemIds) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 6);
    return (SliceLib.getSubslice(_blob, 0, _blob.length).decodeArray_bytes32());
  }

  /** Set itemIds */
  function setItemIds(bytes32 taskId, bytes32[] memory itemIds) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    StoreSwitch.setField(_tableId, _keyTuple, 6, EncodeArray.encode((itemIds)));
  }

  /** Set itemIds (using the specified store) */
  function setItemIds(IStore _store, bytes32 taskId, bytes32[] memory itemIds) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    _store.setField(_tableId, _keyTuple, 6, EncodeArray.encode((itemIds)));
  }

  /** Get the length of itemIds */
  function lengthItemIds(bytes32 taskId) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    uint256 _byteLength = StoreSwitch.getFieldLength(_tableId, _keyTuple, 6, getSchema());
    return _byteLength / 32;
  }

  /** Get the length of itemIds (using the specified store) */
  function lengthItemIds(IStore _store, bytes32 taskId) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    uint256 _byteLength = _store.getFieldLength(_tableId, _keyTuple, 6, getSchema());
    return _byteLength / 32;
  }

  /** Get an item of itemIds (unchecked, returns invalid data if index overflows) */
  function getItemItemIds(bytes32 taskId, uint256 _index) internal view returns (bytes32) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    bytes memory _blob = StoreSwitch.getFieldSlice(_tableId, _keyTuple, 6, getSchema(), _index * 32, (_index + 1) * 32);
    return (Bytes.slice32(_blob, 0));
  }

  /** Get an item of itemIds (using the specified store) (unchecked, returns invalid data if index overflows) */
  function getItemItemIds(IStore _store, bytes32 taskId, uint256 _index) internal view returns (bytes32) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    bytes memory _blob = _store.getFieldSlice(_tableId, _keyTuple, 6, getSchema(), _index * 32, (_index + 1) * 32);
    return (Bytes.slice32(_blob, 0));
  }

  /** Push an element to itemIds */
  function pushItemIds(bytes32 taskId, bytes32 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    StoreSwitch.pushToField(_tableId, _keyTuple, 6, abi.encodePacked((_element)));
  }

  /** Push an element to itemIds (using the specified store) */
  function pushItemIds(IStore _store, bytes32 taskId, bytes32 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    _store.pushToField(_tableId, _keyTuple, 6, abi.encodePacked((_element)));
  }

  /** Pop an element from itemIds */
  function popItemIds(bytes32 taskId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    StoreSwitch.popFromField(_tableId, _keyTuple, 6, 32);
  }

  /** Pop an element from itemIds (using the specified store) */
  function popItemIds(IStore _store, bytes32 taskId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    _store.popFromField(_tableId, _keyTuple, 6, 32);
  }

  /** Update an element of itemIds at `_index` */
  function updateItemIds(bytes32 taskId, uint256 _index, bytes32 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    StoreSwitch.updateInField(_tableId, _keyTuple, 6, _index * 32, abi.encodePacked((_element)));
  }

  /** Update an element of itemIds (using the specified store) at `_index` */
  function updateItemIds(IStore _store, bytes32 taskId, uint256 _index, bytes32 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    _store.updateInField(_tableId, _keyTuple, 6, _index * 32, abi.encodePacked((_element)));
  }

  /** Get itemQuantities */
  function getItemQuantities(bytes32 taskId) internal view returns (uint32[] memory itemQuantities) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 7);
    return (SliceLib.getSubslice(_blob, 0, _blob.length).decodeArray_uint32());
  }

  /** Get itemQuantities (using the specified store) */
  function getItemQuantities(IStore _store, bytes32 taskId) internal view returns (uint32[] memory itemQuantities) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 7);
    return (SliceLib.getSubslice(_blob, 0, _blob.length).decodeArray_uint32());
  }

  /** Set itemQuantities */
  function setItemQuantities(bytes32 taskId, uint32[] memory itemQuantities) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    StoreSwitch.setField(_tableId, _keyTuple, 7, EncodeArray.encode((itemQuantities)));
  }

  /** Set itemQuantities (using the specified store) */
  function setItemQuantities(IStore _store, bytes32 taskId, uint32[] memory itemQuantities) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    _store.setField(_tableId, _keyTuple, 7, EncodeArray.encode((itemQuantities)));
  }

  /** Get the length of itemQuantities */
  function lengthItemQuantities(bytes32 taskId) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    uint256 _byteLength = StoreSwitch.getFieldLength(_tableId, _keyTuple, 7, getSchema());
    return _byteLength / 4;
  }

  /** Get the length of itemQuantities (using the specified store) */
  function lengthItemQuantities(IStore _store, bytes32 taskId) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    uint256 _byteLength = _store.getFieldLength(_tableId, _keyTuple, 7, getSchema());
    return _byteLength / 4;
  }

  /** Get an item of itemQuantities (unchecked, returns invalid data if index overflows) */
  function getItemItemQuantities(bytes32 taskId, uint256 _index) internal view returns (uint32) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    bytes memory _blob = StoreSwitch.getFieldSlice(_tableId, _keyTuple, 7, getSchema(), _index * 4, (_index + 1) * 4);
    return (uint32(Bytes.slice4(_blob, 0)));
  }

  /** Get an item of itemQuantities (using the specified store) (unchecked, returns invalid data if index overflows) */
  function getItemItemQuantities(IStore _store, bytes32 taskId, uint256 _index) internal view returns (uint32) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    bytes memory _blob = _store.getFieldSlice(_tableId, _keyTuple, 7, getSchema(), _index * 4, (_index + 1) * 4);
    return (uint32(Bytes.slice4(_blob, 0)));
  }

  /** Push an element to itemQuantities */
  function pushItemQuantities(bytes32 taskId, uint32 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    StoreSwitch.pushToField(_tableId, _keyTuple, 7, abi.encodePacked((_element)));
  }

  /** Push an element to itemQuantities (using the specified store) */
  function pushItemQuantities(IStore _store, bytes32 taskId, uint32 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    _store.pushToField(_tableId, _keyTuple, 7, abi.encodePacked((_element)));
  }

  /** Pop an element from itemQuantities */
  function popItemQuantities(bytes32 taskId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    StoreSwitch.popFromField(_tableId, _keyTuple, 7, 4);
  }

  /** Pop an element from itemQuantities (using the specified store) */
  function popItemQuantities(IStore _store, bytes32 taskId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    _store.popFromField(_tableId, _keyTuple, 7, 4);
  }

  /** Update an element of itemQuantities at `_index` */
  function updateItemQuantities(bytes32 taskId, uint256 _index, uint32 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    StoreSwitch.updateInField(_tableId, _keyTuple, 7, _index * 4, abi.encodePacked((_element)));
  }

  /** Update an element of itemQuantities (using the specified store) at `_index` */
  function updateItemQuantities(IStore _store, bytes32 taskId, uint256 _index, uint32 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    _store.updateInField(_tableId, _keyTuple, 7, _index * 4, abi.encodePacked((_element)));
  }

  /** Get rewardItemIds */
  function getRewardItemIds(bytes32 taskId) internal view returns (bytes32[] memory rewardItemIds) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 8);
    return (SliceLib.getSubslice(_blob, 0, _blob.length).decodeArray_bytes32());
  }

  /** Get rewardItemIds (using the specified store) */
  function getRewardItemIds(IStore _store, bytes32 taskId) internal view returns (bytes32[] memory rewardItemIds) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 8);
    return (SliceLib.getSubslice(_blob, 0, _blob.length).decodeArray_bytes32());
  }

  /** Set rewardItemIds */
  function setRewardItemIds(bytes32 taskId, bytes32[] memory rewardItemIds) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    StoreSwitch.setField(_tableId, _keyTuple, 8, EncodeArray.encode((rewardItemIds)));
  }

  /** Set rewardItemIds (using the specified store) */
  function setRewardItemIds(IStore _store, bytes32 taskId, bytes32[] memory rewardItemIds) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    _store.setField(_tableId, _keyTuple, 8, EncodeArray.encode((rewardItemIds)));
  }

  /** Get the length of rewardItemIds */
  function lengthRewardItemIds(bytes32 taskId) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    uint256 _byteLength = StoreSwitch.getFieldLength(_tableId, _keyTuple, 8, getSchema());
    return _byteLength / 32;
  }

  /** Get the length of rewardItemIds (using the specified store) */
  function lengthRewardItemIds(IStore _store, bytes32 taskId) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    uint256 _byteLength = _store.getFieldLength(_tableId, _keyTuple, 8, getSchema());
    return _byteLength / 32;
  }

  /** Get an item of rewardItemIds (unchecked, returns invalid data if index overflows) */
  function getItemRewardItemIds(bytes32 taskId, uint256 _index) internal view returns (bytes32) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    bytes memory _blob = StoreSwitch.getFieldSlice(_tableId, _keyTuple, 8, getSchema(), _index * 32, (_index + 1) * 32);
    return (Bytes.slice32(_blob, 0));
  }

  /** Get an item of rewardItemIds (using the specified store) (unchecked, returns invalid data if index overflows) */
  function getItemRewardItemIds(IStore _store, bytes32 taskId, uint256 _index) internal view returns (bytes32) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    bytes memory _blob = _store.getFieldSlice(_tableId, _keyTuple, 8, getSchema(), _index * 32, (_index + 1) * 32);
    return (Bytes.slice32(_blob, 0));
  }

  /** Push an element to rewardItemIds */
  function pushRewardItemIds(bytes32 taskId, bytes32 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    StoreSwitch.pushToField(_tableId, _keyTuple, 8, abi.encodePacked((_element)));
  }

  /** Push an element to rewardItemIds (using the specified store) */
  function pushRewardItemIds(IStore _store, bytes32 taskId, bytes32 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    _store.pushToField(_tableId, _keyTuple, 8, abi.encodePacked((_element)));
  }

  /** Pop an element from rewardItemIds */
  function popRewardItemIds(bytes32 taskId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    StoreSwitch.popFromField(_tableId, _keyTuple, 8, 32);
  }

  /** Pop an element from rewardItemIds (using the specified store) */
  function popRewardItemIds(IStore _store, bytes32 taskId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    _store.popFromField(_tableId, _keyTuple, 8, 32);
  }

  /** Update an element of rewardItemIds at `_index` */
  function updateRewardItemIds(bytes32 taskId, uint256 _index, bytes32 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    StoreSwitch.updateInField(_tableId, _keyTuple, 8, _index * 32, abi.encodePacked((_element)));
  }

  /** Update an element of rewardItemIds (using the specified store) at `_index` */
  function updateRewardItemIds(IStore _store, bytes32 taskId, uint256 _index, bytes32 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    _store.updateInField(_tableId, _keyTuple, 8, _index * 32, abi.encodePacked((_element)));
  }

  /** Get rewardItemQuantities */
  function getRewardItemQuantities(bytes32 taskId) internal view returns (uint32[] memory rewardItemQuantities) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 9);
    return (SliceLib.getSubslice(_blob, 0, _blob.length).decodeArray_uint32());
  }

  /** Get rewardItemQuantities (using the specified store) */
  function getRewardItemQuantities(
    IStore _store,
    bytes32 taskId
  ) internal view returns (uint32[] memory rewardItemQuantities) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 9);
    return (SliceLib.getSubslice(_blob, 0, _blob.length).decodeArray_uint32());
  }

  /** Set rewardItemQuantities */
  function setRewardItemQuantities(bytes32 taskId, uint32[] memory rewardItemQuantities) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    StoreSwitch.setField(_tableId, _keyTuple, 9, EncodeArray.encode((rewardItemQuantities)));
  }

  /** Set rewardItemQuantities (using the specified store) */
  function setRewardItemQuantities(IStore _store, bytes32 taskId, uint32[] memory rewardItemQuantities) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    _store.setField(_tableId, _keyTuple, 9, EncodeArray.encode((rewardItemQuantities)));
  }

  /** Get the length of rewardItemQuantities */
  function lengthRewardItemQuantities(bytes32 taskId) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    uint256 _byteLength = StoreSwitch.getFieldLength(_tableId, _keyTuple, 9, getSchema());
    return _byteLength / 4;
  }

  /** Get the length of rewardItemQuantities (using the specified store) */
  function lengthRewardItemQuantities(IStore _store, bytes32 taskId) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    uint256 _byteLength = _store.getFieldLength(_tableId, _keyTuple, 9, getSchema());
    return _byteLength / 4;
  }

  /** Get an item of rewardItemQuantities (unchecked, returns invalid data if index overflows) */
  function getItemRewardItemQuantities(bytes32 taskId, uint256 _index) internal view returns (uint32) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    bytes memory _blob = StoreSwitch.getFieldSlice(_tableId, _keyTuple, 9, getSchema(), _index * 4, (_index + 1) * 4);
    return (uint32(Bytes.slice4(_blob, 0)));
  }

  /** Get an item of rewardItemQuantities (using the specified store) (unchecked, returns invalid data if index overflows) */
  function getItemRewardItemQuantities(IStore _store, bytes32 taskId, uint256 _index) internal view returns (uint32) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    bytes memory _blob = _store.getFieldSlice(_tableId, _keyTuple, 9, getSchema(), _index * 4, (_index + 1) * 4);
    return (uint32(Bytes.slice4(_blob, 0)));
  }

  /** Push an element to rewardItemQuantities */
  function pushRewardItemQuantities(bytes32 taskId, uint32 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    StoreSwitch.pushToField(_tableId, _keyTuple, 9, abi.encodePacked((_element)));
  }

  /** Push an element to rewardItemQuantities (using the specified store) */
  function pushRewardItemQuantities(IStore _store, bytes32 taskId, uint32 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    _store.pushToField(_tableId, _keyTuple, 9, abi.encodePacked((_element)));
  }

  /** Pop an element from rewardItemQuantities */
  function popRewardItemQuantities(bytes32 taskId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    StoreSwitch.popFromField(_tableId, _keyTuple, 9, 4);
  }

  /** Pop an element from rewardItemQuantities (using the specified store) */
  function popRewardItemQuantities(IStore _store, bytes32 taskId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    _store.popFromField(_tableId, _keyTuple, 9, 4);
  }

  /** Update an element of rewardItemQuantities at `_index` */
  function updateRewardItemQuantities(bytes32 taskId, uint256 _index, uint32 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    StoreSwitch.updateInField(_tableId, _keyTuple, 9, _index * 4, abi.encodePacked((_element)));
  }

  /** Update an element of rewardItemQuantities (using the specified store) at `_index` */
  function updateRewardItemQuantities(IStore _store, bytes32 taskId, uint256 _index, uint32 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    _store.updateInField(_tableId, _keyTuple, 9, _index * 4, abi.encodePacked((_element)));
  }

  /** Get the full data */
  function get(bytes32 taskId) internal view returns (TaskConfigData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    bytes memory _blob = StoreSwitch.getRecord(_tableId, _keyTuple, getSchema());
    return decode(_blob);
  }

  /** Get the full data (using the specified store) */
  function get(IStore _store, bytes32 taskId) internal view returns (TaskConfigData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    bytes memory _blob = _store.getRecord(_tableId, _keyTuple, getSchema());
    return decode(_blob);
  }

  /** Set the full data using individual values */
  function set(
    bytes32 taskId,
    uint32 level,
    uint32 dupPeriod,
    uint32 rewardExp,
    uint256 rewardCoins,
    uint256 rewardDiamonds,
    bool itemConsumed,
    bytes32[] memory itemIds,
    uint32[] memory itemQuantities,
    bytes32[] memory rewardItemIds,
    uint32[] memory rewardItemQuantities
  ) internal {
    bytes memory _data = encode(
      level,
      dupPeriod,
      rewardExp,
      rewardCoins,
      rewardDiamonds,
      itemConsumed,
      itemIds,
      itemQuantities,
      rewardItemIds,
      rewardItemQuantities
    );

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    StoreSwitch.setRecord(_tableId, _keyTuple, _data);
  }

  /** Set the full data using individual values (using the specified store) */
  function set(
    IStore _store,
    bytes32 taskId,
    uint32 level,
    uint32 dupPeriod,
    uint32 rewardExp,
    uint256 rewardCoins,
    uint256 rewardDiamonds,
    bool itemConsumed,
    bytes32[] memory itemIds,
    uint32[] memory itemQuantities,
    bytes32[] memory rewardItemIds,
    uint32[] memory rewardItemQuantities
  ) internal {
    bytes memory _data = encode(
      level,
      dupPeriod,
      rewardExp,
      rewardCoins,
      rewardDiamonds,
      itemConsumed,
      itemIds,
      itemQuantities,
      rewardItemIds,
      rewardItemQuantities
    );

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    _store.setRecord(_tableId, _keyTuple, _data);
  }

  /** Set the full data using the data struct */
  function set(bytes32 taskId, TaskConfigData memory _table) internal {
    set(
      taskId,
      _table.level,
      _table.dupPeriod,
      _table.rewardExp,
      _table.rewardCoins,
      _table.rewardDiamonds,
      _table.itemConsumed,
      _table.itemIds,
      _table.itemQuantities,
      _table.rewardItemIds,
      _table.rewardItemQuantities
    );
  }

  /** Set the full data using the data struct (using the specified store) */
  function set(IStore _store, bytes32 taskId, TaskConfigData memory _table) internal {
    set(
      _store,
      taskId,
      _table.level,
      _table.dupPeriod,
      _table.rewardExp,
      _table.rewardCoins,
      _table.rewardDiamonds,
      _table.itemConsumed,
      _table.itemIds,
      _table.itemQuantities,
      _table.rewardItemIds,
      _table.rewardItemQuantities
    );
  }

  /** Decode the tightly packed blob using this table's schema */
  function decode(bytes memory _blob) internal view returns (TaskConfigData memory _table) {
    // 77 is the total byte length of static data
    PackedCounter _encodedLengths = PackedCounter.wrap(Bytes.slice32(_blob, 77));

    _table.level = (uint32(Bytes.slice4(_blob, 0)));

    _table.dupPeriod = (uint32(Bytes.slice4(_blob, 4)));

    _table.rewardExp = (uint32(Bytes.slice4(_blob, 8)));

    _table.rewardCoins = (uint256(Bytes.slice32(_blob, 12)));

    _table.rewardDiamonds = (uint256(Bytes.slice32(_blob, 44)));

    _table.itemConsumed = (_toBool(uint8(Bytes.slice1(_blob, 76))));

    // Store trims the blob if dynamic fields are all empty
    if (_blob.length > 77) {
      uint256 _start;
      // skip static data length + dynamic lengths word
      uint256 _end = 109;

      _start = _end;
      _end += _encodedLengths.atIndex(0);
      _table.itemIds = (SliceLib.getSubslice(_blob, _start, _end).decodeArray_bytes32());

      _start = _end;
      _end += _encodedLengths.atIndex(1);
      _table.itemQuantities = (SliceLib.getSubslice(_blob, _start, _end).decodeArray_uint32());

      _start = _end;
      _end += _encodedLengths.atIndex(2);
      _table.rewardItemIds = (SliceLib.getSubslice(_blob, _start, _end).decodeArray_bytes32());

      _start = _end;
      _end += _encodedLengths.atIndex(3);
      _table.rewardItemQuantities = (SliceLib.getSubslice(_blob, _start, _end).decodeArray_uint32());
    }
  }

  /** Tightly pack full data using this table's schema */
  function encode(
    uint32 level,
    uint32 dupPeriod,
    uint32 rewardExp,
    uint256 rewardCoins,
    uint256 rewardDiamonds,
    bool itemConsumed,
    bytes32[] memory itemIds,
    uint32[] memory itemQuantities,
    bytes32[] memory rewardItemIds,
    uint32[] memory rewardItemQuantities
  ) internal view returns (bytes memory) {
    uint40[] memory _counters = new uint40[](4);
    _counters[0] = uint40(itemIds.length * 32);
    _counters[1] = uint40(itemQuantities.length * 4);
    _counters[2] = uint40(rewardItemIds.length * 32);
    _counters[3] = uint40(rewardItemQuantities.length * 4);
    PackedCounter _encodedLengths = PackedCounterLib.pack(_counters);

    return
      abi.encodePacked(
        level,
        dupPeriod,
        rewardExp,
        rewardCoins,
        rewardDiamonds,
        itemConsumed,
        _encodedLengths.unwrap(),
        EncodeArray.encode((itemIds)),
        EncodeArray.encode((itemQuantities)),
        EncodeArray.encode((rewardItemIds)),
        EncodeArray.encode((rewardItemQuantities))
      );
  }

  /** Encode keys as a bytes32 array using this table's schema */
  function encodeKeyTuple(bytes32 taskId) internal pure returns (bytes32[] memory _keyTuple) {
    _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;
  }

  /* Delete all data for given keys */
  function deleteRecord(bytes32 taskId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /* Delete all data for given keys (using the specified store) */
  function deleteRecord(IStore _store, bytes32 taskId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = taskId;

    _store.deleteRecord(_tableId, _keyTuple);
  }
}

function _toBool(uint8 value) pure returns (bool result) {
  assembly {
    result := value
  }
}
