// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Address2User, Address2UserTableId } from "./tables/Address2User.sol";
import { UserMainAddress, UserMainAddressTableId } from "./tables/UserMainAddress.sol";
import { ItemList, ItemListData, ItemListTableId } from "./tables/ItemList.sol";
import { Tradable, TradableTableId } from "./tables/Tradable.sol";
import { Cats, CatsData, CatsTableId } from "./tables/Cats.sol";
import { CatBuff, CatBuffData, CatBuffTableId } from "./tables/CatBuff.sol";
import { UserAdoptions, UserAdoptionsTableId } from "./tables/UserAdoptions.sol";
import { UserCatList, UserCatListTableId } from "./tables/UserCatList.sol";
import { UserCats, UserCatsData, UserCatsTableId } from "./tables/UserCats.sol";
import { CatConfig, CatConfigData, CatConfigTableId } from "./tables/CatConfig.sol";
import { UserRoomExpansion, UserRoomExpansionData, UserRoomExpansionTableId } from "./tables/UserRoomExpansion.sol";
import { AutoFeeder, AutoFeederData, AutoFeederTableId } from "./tables/AutoFeeder.sol";
import { UserStatus, UserStatusData, UserStatusTableId } from "./tables/UserStatus.sol";
import { UserCatAlbum, UserCatAlbumData, UserCatAlbumTableId } from "./tables/UserCatAlbum.sol";
import { Travel, TravelData, TravelTableId } from "./tables/Travel.sol";
import { UserItems, UserItemsData, UserItemsTableId } from "./tables/UserItems.sol";
import { ItemConfig, ItemConfigData, ItemConfigTableId } from "./tables/ItemConfig.sol";
import { FoodConfig, FoodConfigData, FoodConfigTableId } from "./tables/FoodConfig.sol";
import { TaskConfig, TaskConfigData, TaskConfigTableId } from "./tables/TaskConfig.sol";
import { ChoresConfig, ChoresConfigData, ChoresConfigTableId } from "./tables/ChoresConfig.sol";
import { Shop, ShopData, ShopTableId } from "./tables/Shop.sol";
import { EventTimes, EventTimesTableId } from "./tables/EventTimes.sol";
import { GlobalAddressConfig, GlobalAddressConfigTableId } from "./tables/GlobalAddressConfig.sol";
