// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IAdminConfigSystem {
  function setupTokenAddress(address tokenAddress) external;

  function setupRandomSource(address randomSource) external;

  function setupPlayerInitConfig(uint256 initCoins) external;

  function setupPlayerInitItem(bytes32[] memory itemIds) external;
}
