// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IAutoFeederSystem {
  function autoFeedAll(bytes32[] calldata catIds) external;

  function calculateAutoFeed(uint32 hunger, bytes32 userId, bytes32 catId) external view returns (uint32, uint32);

  function autoFeed(bytes32 catId) external;
}
