// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IBuffConfigSystem {
  function setupBuffTypeConfig(uint32[] memory buffTypes, uint256[] memory attributes) external;

  function setBuffTypeExtraAttributes(uint32 buffType, uint256[] memory extraAttributes) external;

  function setupBuffConfig(
    bytes32[] memory buffIds,
    uint32[] memory buffTypes,
    uint256[] memory buffValues,
    uint256[] memory durations
  ) external;

  function setBuffConfigExtraValues(bytes32 buffId, uint256[] memory extraValues) external;
}
