// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ICatSystem {
  function adoptInitCat() external;

  function feed(bytes32 catId, uint256 itemId, uint32 quantity) external;
}
