// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ICatLevelConfigSystem {
  function setCatLevelConfig(
    uint32 catLevel,
    uint32 hungerLimit,
    uint32 funLimit,
    uint32 expLimit,
    uint32 coinBase
  ) external;
}
