// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IFoodConfigSystem {
  function setFood(
    bytes32 itemId,
    uint32 hunger,
    uint32 dropRate,
    uint32 maxItemQuantity,
    uint32 hungerCoinRate,
    string memory name,
    string memory uri
  ) external;
}
