// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ILevelConfigSystem {
  function setUserLevelConfig(uint32 userLevel, uint32 expLimit) external;

  function setupUserLevelConfig(uint32[] memory userLevels, uint32[] memory expLimits) external;

  function setUserLevelConfigs(uint32[] calldata userLevels, uint32[] calldata expLimits) external;

  function setCatLevelConfig(uint32 catLevel, uint32 hungerLimit, uint32 expLimit) external;

  function setupCatLevelConfig(
    uint32[] memory catLevels,
    uint32[] memory hungerLimits,
    uint32[] memory expLimits
  ) external;

  function setCatFriendshipLevelConfig(uint32 friendshipLevel, uint32 expLimit, uint32 starvingTimeLimit) external;

  function setupCatFriendshipLevelConfig(
    uint32[] memory friendshipLevels,
    uint32[] memory expLimits,
    uint32[] memory starvingTimeLimits
  ) external;
}
