// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IPetSystem {
  function getStatus(bytes32 catId) external returns (uint32, uint32);

  function getHunger(bytes32 catId) external returns (uint32);

  function getFun(bytes32 catId) external returns (uint32);

  function touch(bytes32 catId) external;

  function feed(bytes32 catId, bytes32 itemId, uint32 quantity) external;

  function recall(bytes32 catId) external;

  function getHobbyHungerConsumption(bytes32 catId) external view returns (uint32);

  function updateHobbyHungerConsumption(bytes32 catId) external returns (uint32);

  function updateStarvingStartTime(bytes32 catId) external;

  function starvingCheck(bytes32 catId) external;

  function calculateBasicHungerConsumption(bytes32 catId, uint256 timeDiff) external view returns (uint32);

  function calculateBasicFunConsumption(bytes32 catId, uint256 timeDiff) external view returns (uint32);

  function estimateCatStatus(bytes32 catId) external view returns (uint32, uint32);

  function liveUpdate(bytes32 catId) external;
}
