// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IRandDisturbHelperSystem {
  function getSimpleRandDisturbResult(
    uint256 baseValue,
    uint256 disturbRange,
    uint256 randSeed
  ) external pure returns (uint256);
}
