// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ISampleOpenConfigSystem {
  function setSampleConfig(
    bytes32 sampleId,
    uint8 method,
    uint16[] memory indices,
    uint16[] memory rates,
    uint32[] memory accWeights
  ) external;

  function addSampleConfig(
    bytes32 sampleId,
    uint8 method,
    uint16 index,
    uint8 weight,
    uint16 rate,
    uint32 accWeight
  ) external;

  function changeSampleConfigDesigner(bytes32 sampleId, address newDesigner) external;

  function getSampleIndex(
    bytes32 sampleId,
    uint256 randSeed,
    string memory salt,
    uint256 length
  ) external view returns (uint256);

  function getSampleIndex(bytes32 sampleId, uint256 randSeed, uint256 length) external view returns (uint256);

  function getSampleIndex(bytes32 sampleId, uint256 randSeed) external view returns (uint256);

  function getSampleIndices(
    bytes32 sampleId,
    uint256 randSeed,
    string memory salt,
    uint256 sampleCount,
    uint256 totalCount
  ) external view returns (uint256[] memory);
}
