// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ITaskConfigSystem {
  function setTask(
    bytes32 taskId,
    uint32 level,
    uint32 dupPeriod,
    uint32 rewardExp,
    uint256 rewardCoins,
    uint256 rewardDiamonds,
    bool itemConsumed,
    bytes32[] memory itemIds,
    uint32[] memory itemQuantities,
    bytes32[] memory rewardItemIds,
    uint32[] memory rewardItemQuantities,
    string memory uri,
    string memory name
  ) external;
}
