// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ITimeZoneSystem {
  function getTimeZoneTimestamp(bytes32 userId) external view returns (uint);

  function getTimeUnitNum(uint timezoneTimestamp, uint timeGapSeconds) external pure returns (uint);

  function getDayNum(uint timezoneTimestamp) external pure returns (uint32);

  function getWeekNum(uint timezoneTimestamp) external pure returns (uint32);

  function getMonthNum(uint timezoneTimestamp) external pure returns (uint32);

  function getYearNum(uint timezoneTimestamp) external pure returns (uint32);

  function signedNumber(uint32 number, bool sign) external pure returns (int64);

  function changeTimeZone(bytes32 userId, uint32 newTimezoneOffset, bool newTimeZoneSign) external;
}
