// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IUserLevelConfigSystem {
  function setUserLevelConfig(uint32 userLevel, uint32 expLimit) external;
}
