// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IUserSystem {
  function userExist(address userAddress) external view returns (bool);

  function registerUser() external;

  function changeMainAddress(address newMainAddress) external;

  function unBindUser() external;

  function attachToUser(address addressToAttach) external;
}
