// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { IBaseWorld } from "@latticexyz/world/src/interfaces/IBaseWorld.sol";

import { IAdminConfigSystem } from "./IAdminConfigSystem.sol";
import { IAutoFeederSystem } from "./IAutoFeederSystem.sol";
import { IBuffConfigSystem } from "./IBuffConfigSystem.sol";
import { IFoodConfigSystem } from "./IFoodConfigSystem.sol";
import { IHobbyConfigSystem } from "./IHobbyConfigSystem.sol";
import { IHobbyHelperSystem } from "./IHobbyHelperSystem.sol";
import { IHobbyOpenConfigSystem } from "./IHobbyOpenConfigSystem.sol";
import { IHobbySystem } from "./IHobbySystem.sol";
import { IItemConfigSystem } from "./IItemConfigSystem.sol";
import { ILevelConfigSystem } from "./ILevelConfigSystem.sol";
import { IPeriodEventsSystem } from "./IPeriodEventsSystem.sol";
import { IPetConfigSystem } from "./IPetConfigSystem.sol";
import { IPetHelperSystem } from "./IPetHelperSystem.sol";
import { IPetSystem } from "./IPetSystem.sol";
import { IQuantityHelperSystem } from "./IQuantityHelperSystem.sol";
import { ISampleOpenConfigSystem } from "./ISampleOpenConfigSystem.sol";
import { IShopConfigSystem } from "./IShopConfigSystem.sol";
import { IShopSystem } from "./IShopSystem.sol";
import { ITaskConfigSystem } from "./ITaskConfigSystem.sol";
import { ITaskSystem } from "./ITaskSystem.sol";
import { IUIDHelperSystem } from "./IUIDHelperSystem.sol";
import { IUserOpenConfigSystem } from "./IUserOpenConfigSystem.sol";
import { IUserSystem } from "./IUserSystem.sol";

/**
 * The IWorld interface includes all systems dynamically added to the World
 * during the deploy process.
 */
interface IWorld is
  IBaseWorld,
  IAdminConfigSystem,
  IAutoFeederSystem,
  IBuffConfigSystem,
  IFoodConfigSystem,
  IHobbyConfigSystem,
  IHobbyHelperSystem,
  IHobbyOpenConfigSystem,
  IHobbySystem,
  IItemConfigSystem,
  ILevelConfigSystem,
  IPeriodEventsSystem,
  IPetConfigSystem,
  IPetHelperSystem,
  IPetSystem,
  IQuantityHelperSystem,
  ISampleOpenConfigSystem,
  IShopConfigSystem,
  IShopSystem,
  ITaskConfigSystem,
  ITaskSystem,
  IUIDHelperSystem,
  IUserOpenConfigSystem,
  IUserSystem
{

}
